using System.CodeDom.Compiler;
using System.Web.Mvc;
using System.Web.WebPages;
using Ilaro.Admin.ViewModels;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilaro.Admin.Views.IlaroAdmin.DisplayTemplates
{
    [GeneratedCode("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Views/IlaroAdmin/DisplayTemplates/BoolPartial.cshtml")]
    public partial class _BoolPartial : WebViewPage<CellValueViewModel>
    {
        public _BoolPartial()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\IlaroAdmin\DisplayTemplates\BoolPartial.cshtml"
 if (Model.BoolValue == true)
{

            
            #line default
            #line hidden
WriteLiteral("    <i");

WriteLiteral(" class=\"glyphicon glyphicon-ok\"");

WriteLiteral("></i>\r\n");

            
            #line 6 "..\..\Views\IlaroAdmin\DisplayTemplates\BoolPartial.cshtml"
}
else if (Model.BoolValue == false)
{ 

            
            #line default
            #line hidden
WriteLiteral("    <i");

WriteLiteral(" class=\"glyphicon glyphicon-remove\"");

WriteLiteral("></i>\r\n");

            
            #line 10 "..\..\Views\IlaroAdmin\DisplayTemplates\BoolPartial.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
