using System.CodeDom.Compiler;
using System.Web.Mvc;
using System.Web.WebPages;
using Ilaro.Admin.ViewModels;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilaro.Admin.Views.IlaroAdmin.DisplayTemplates
{
    [GeneratedCode("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Views/IlaroAdmin/DisplayTemplates/PasswordPartial.cshtml")]
    public partial class _PasswordPartial : WebViewPage<CellValueViewModel>
    {
        public _PasswordPartial()
        {
        }
        public override void Execute()
        {
WriteLiteral("***\r\n");

        }
    }
}
#pragma warning restore 1591
