#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Ilaro.Admin;
    using Ilaro.Admin.Core;
    using Ilaro.Admin.Extensions;
    using Ilaro.Admin.Models;
    using Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/IlaroAdmin/Views/Shared/DisplayTemplates/BoolPartial.cshtml")]
    public partial class _Areas_IlaroAdmin_Views_Shared_DisplayTemplates_BoolPartial_cshtml_ : System.Web.Mvc.WebViewPage<CellValue>
    {
        public _Areas_IlaroAdmin_Views_Shared_DisplayTemplates_BoolPartial_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\IlaroAdmin\Views\Shared\DisplayTemplates\BoolPartial.cshtml"
 if (Model.AsBool == true)
{

            
            #line default
            #line hidden
WriteLiteral("    <i");

WriteLiteral(" class=\"glyphicon glyphicon-ok\"");

WriteLiteral("></i>\r\n");

            
            #line 6 "..\..\Areas\IlaroAdmin\Views\Shared\DisplayTemplates\BoolPartial.cshtml"
}
else if (Model.AsBool == false)
{

            
            #line default
            #line hidden
WriteLiteral("    <i");

WriteLiteral(" class=\"glyphicon glyphicon-remove\"");

WriteLiteral("></i>\r\n");

            
            #line 10 "..\..\Areas\IlaroAdmin\Views\Shared\DisplayTemplates\BoolPartial.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
