#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Ilaro.Admin;
    using Ilaro.Admin.Core;
    using Ilaro.Admin.Extensions;
    using Ilaro.Admin.Models;
    using Ilaro.Admin.Models.Paging;
    using Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/IlaroAdmin/Views/Shared/DisplayTemplates/DbImagePartial.cshtml")]
    public partial class _Areas_IlaroAdmin_Views_Shared_DisplayTemplates_DbImagePartial_cshtml_ : System.Web.Mvc.WebViewPage<CellValue>
    {
        public _Areas_IlaroAdmin_Views_Shared_DisplayTemplates_DbImagePartial_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("<img");

WriteAttribute("src", Tuple.Create(" src=\"", 24), Tuple.Create("\"", 94)
, Tuple.Create(Tuple.Create("", 30), Tuple.Create("data:image/jpg;base64,", 30), true)
            
            #line 3 "..\..\Areas\IlaroAdmin\Views\Shared\DisplayTemplates\DbImagePartial.cshtml"
, Tuple.Create(Tuple.Create("", 52), Tuple.Create<System.Object, System.Int32>(Convert.ToBase64String((byte[])Model.Raw)
            
            #line default
            #line hidden
, 52), false)
);

WriteLiteral(" class=\"img-polaroid\"");

WriteLiteral(" />\r\n");

        }
    }
}
#pragma warning restore 1591
