//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyTitle("Ilaro.Admin.Ninject")]
[assembly: AssemblyProduct("Ilaro.Admin.Ninject")]
[assembly: AssemblyVersion("0.5.1")]
[assembly: AssemblyFileVersion("0.5.1")]
[assembly: AssemblyInformationalVersion("0.5.1")]
[assembly: AssemblyCopyright("Copyright © Robert Gonek 2014-2016")]

