#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Ilaro.Admin.Commons.Paging;
    using Ilaro.Admin.Core;
    using Ilaro.Admin.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/IlaroAdmin/EditorTemplates/CheckboxPartial.cshtml")]
    public partial class _Views_IlaroAdmin_EditorTemplates_CheckboxPartial_cshtml_ : System.Web.Mvc.WebViewPage<Property>
    {
        public _Views_IlaroAdmin_EditorTemplates_CheckboxPartial_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\IlaroAdmin\EditorTemplates\CheckboxPartial.cshtml"
  Html.ClearPrefix();
            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"col-md-offset-2\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(">\r\n            <label");

WriteAttribute("for", Tuple.Create(" for=\"", 152), Tuple.Create("\"", 178)
            
            #line 7 "..\..\Views\IlaroAdmin\EditorTemplates\CheckboxPartial.cshtml"
, Tuple.Create(Tuple.Create("", 158), Tuple.Create<System.Object, System.Int32>(Html.Id(Model.Name)
            
            #line default
            #line hidden
, 158), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 8 "..\..\Views\IlaroAdmin\EditorTemplates\CheckboxPartial.cshtml"
           Write(Model.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 9 "..\..\Views\IlaroAdmin\EditorTemplates\CheckboxPartial.cshtml"
           Write(Html.Condition(Model.IsRequired, () => "<span class=\"text-danger\">*</span>"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 10 "..\..\Views\IlaroAdmin\EditorTemplates\CheckboxPartial.cshtml"
           Write(Html.CheckBox(Model.Name, Model.Value.AsBool.GetValueOrDefault(), Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </label>\r\n        </div>\r\n");

WriteLiteral("        ");

            
            #line 13 "..\..\Views\IlaroAdmin\EditorTemplates\CheckboxPartial.cshtml"
   Write(Html.Condition(!string.IsNullOrEmpty(Model.Description), () => "<span class=\"description\">" + Model.Description + "</span>"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

WriteLiteral("    ");

            
            #line 15 "..\..\Views\IlaroAdmin\EditorTemplates\CheckboxPartial.cshtml"
Write(Html.ValidationMessage(Model.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>");

        }
    }
}
#pragma warning restore 1591
