#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilaro.Admin.Views.IlaroAdmin.EditorTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Ilaro.Admin.Commons.Paging;
    using Ilaro.Admin.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/IlaroAdmin/EditorTemplates/FilePartial.cshtml")]
    public partial class _FilePartial : System.Web.Mvc.WebViewPage<Ilaro.Admin.ViewModels.PropertyViewModel>
    {
        public _FilePartial()
        {
        }
        public override void Execute()
        {
WriteLiteral("<label");

WriteAttribute("for", Tuple.Create(" for=\"", 57), Tuple.Create("\"", 83)
            
            #line 3 "..\..\Views\IlaroAdmin\EditorTemplates\FilePartial.cshtml"
, Tuple.Create(Tuple.Create("", 63), Tuple.Create<System.Object, System.Int32>(Html.Id(Model.Name)
            
            #line default
            #line hidden
, 63), false)
);

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">");

            
            #line 3 "..\..\Views\IlaroAdmin\EditorTemplates\FilePartial.cshtml"
                                                   Write(Model.DisplayName);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 3 "..\..\Views\IlaroAdmin\EditorTemplates\FilePartial.cshtml"
                                                                      Write(Html.Condition(Model.IsRequired, () => "<span class=\"text-error\">*</span>"));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n<div");

WriteLiteral(" class=\"controls\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"fileupload fileupload-new\"");

WriteLiteral(" data-provides=\"fileupload\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"input-append\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"uneditable-input\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"icon-file fileupload-exists\"");

WriteLiteral("></i>\r\n                <span");

WriteLiteral(" class=\"fileupload-preview\"");

WriteLiteral("></span>\r\n            </div>\r\n            <span");

WriteLiteral(" class=\"btn btn-file\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"fileupload-new\"");

WriteLiteral(">Choose file</span>\r\n                <span");

WriteLiteral(" class=\"fileupload-exists\"");

WriteLiteral(">Change</span>\r\n                <input");

WriteAttribute("id", Tuple.Create(" id=\"", 720), Tuple.Create("\"", 745)
            
            #line 14 "..\..\Views\IlaroAdmin\EditorTemplates\FilePartial.cshtml"
, Tuple.Create(Tuple.Create("", 725), Tuple.Create<System.Object, System.Int32>(Html.Id(Model.Name)
            
            #line default
            #line hidden
, 725), false)
);

WriteAttribute("name", Tuple.Create(" name=\"", 746), Tuple.Create("\"", 775)
            
            #line 14 "..\..\Views\IlaroAdmin\EditorTemplates\FilePartial.cshtml"
, Tuple.Create(Tuple.Create("", 753), Tuple.Create<System.Object, System.Int32>(Html.Name(Model.Name)
            
            #line default
            #line hidden
, 753), false)
);

WriteLiteral(" type=\"file\"");

WriteLiteral(" />\r\n            </span>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"btn fileupload-exists\"");

WriteLiteral(" data-dismiss=\"fileupload\"");

WriteLiteral(">Usuń</a>\r\n        </div>\r\n    </div>\r\n\r\n");

WriteLiteral("    ");

            
            #line 20 "..\..\Views\IlaroAdmin\EditorTemplates\FilePartial.cshtml"
Write(Html.Condition(!string.IsNullOrEmpty(Model.Description), () => "<span class=\"help-block\">" + Model.Description + "</span>"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
