#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Ilaro.Admin;
    using Ilaro.Admin.Core;
    using Ilaro.Admin.Core.Extensions;
    using Ilaro.Admin.Extensions;
    using Ilaro.Admin.Models;
    using Ilaro.Admin.Models.Paging;
    using Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/IlaroAdmin/Views/Entities/_Paging.cshtml")]
    public partial class _Areas_IlaroAdmin_Views_Entities__Paging_cshtml : System.Web.Mvc.WebViewPage<PagerInfo>
    {

#line 94 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
public System.Web.WebPages.HelperResult PagerLink(string linkText, int pageNumber, string url, string rel = "", string @classes = "")
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 95 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
 
    url = string.Format(url, pageNumber);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <li");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 2831), Tuple.Create("\"", 2847)

#line 97 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
, Tuple.Create(Tuple.Create("", 2839), Tuple.Create<System.Object, System.Int32>(classes

#line default
#line hidden
, 2839), false)
);

WriteLiteralTo(__razor_helper_writer, "><a");

WriteAttributeTo(__razor_helper_writer, "href", Tuple.Create(" href=\"", 2851), Tuple.Create("\"", 2862)

#line 97 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
, Tuple.Create(Tuple.Create("", 2858), Tuple.Create<System.Object, System.Int32>(url

#line default
#line hidden
, 2858), false)
);

WriteAttributeTo(__razor_helper_writer, "rel", Tuple.Create(" rel=\"", 2863), Tuple.Create("\"", 2873)

#line 97 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
, Tuple.Create(Tuple.Create("", 2869), Tuple.Create<System.Object, System.Int32>(rel

#line default
#line hidden
, 2869), false)
);

WriteLiteralTo(__razor_helper_writer, ">");


#line 97 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
                     WriteTo(__razor_helper_writer, linkText);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</a></li>\r\n");


#line 98 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"


#line default
#line hidden
});

#line 98 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
}
#line default
#line hidden

        public _Areas_IlaroAdmin_Views_Entities__Paging_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 10 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
 if (Model.TotalPages <= 1)
{
    return;
}

            
            #line default
            #line hidden
            
            #line 14 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
  
    const int nrOfPagesToDisplay = 10;

            
            #line default
            #line hidden
WriteLiteral("\r\n<ul");

WriteLiteral(" id=\"pagination-entity\"");

WriteLiteral(" class=\"pagination\"");

WriteLiteral(">\r\n");

            
            #line 18 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
    
            
            #line default
            #line hidden
            
            #line 18 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
      
        // Make some calculation
        var start = 1;
        var end = Model.TotalPages;
        if (Model.TotalPages > nrOfPagesToDisplay)
        {
            var middle = (int)Math.Ceiling(nrOfPagesToDisplay / 2d) - 1;
            var below = (Model.Current - middle);
            var above = (Model.Current + middle);

            if (below < 4)
            {
                above = nrOfPagesToDisplay;
                below = 1;
            }
            else if (above > (Model.TotalPages - 4))
            {
                above = Model.TotalPages;
                below = (Model.TotalPages - nrOfPagesToDisplay);
            }

            start = below;
            end = above;
        }
    
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    ");

WriteLiteral("\r\n");

            
            #line 45 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
    
            
            #line default
            #line hidden
            
            #line 45 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
     if (Model.Current > 1)
    {
        
            
            #line default
            #line hidden
            
            #line 47 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
   Write(PagerLink(IlaroAdminResources.PreviousPage, Model.Current - 1, Model.Url, "prev"));

            
            #line default
            #line hidden
            
            #line 47 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
                                                                                          
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <li");

WriteLiteral(" class=\"disabled\"");

WriteLiteral("><span>");

            
            #line 51 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
                              Write(IlaroAdminResources.PreviousPage);

            
            #line default
            #line hidden
WriteLiteral("</span></li>\r\n");

            
            #line 52 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

WriteLiteral("\r\n");

            
            #line 55 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
    
            
            #line default
            #line hidden
            
            #line 55 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
     if (start > 3)
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 57 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
         Write(PagerLink("1", 1, Model.Url));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 58 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
         Write(PagerLink("2", 2, Model.Url));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        <li");

WriteLiteral(" class=\"disabled\"");

WriteLiteral("><span>...</span></li>\r\n");

            
            #line 60 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
    }

    
            
            #line default
            #line hidden
            
            #line 62 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
                      

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 63 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
     for (var i = start; i <= end; i++)
    {
        if (i == Model.Current || (Model.Current <= 0 && i == 0))
        {

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 67 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
             Write(PagerLink(i.ToString(), i, Model.Url, "", "active"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 68 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 71 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
             Write(PagerLink(i.ToString(), i, Model.Url));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 72 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

WriteLiteral("\r\n");

            
            #line 76 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
    
            
            #line default
            #line hidden
            
            #line 76 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
     if (end < (Model.TotalPages - 3))
    {

            
            #line default
            #line hidden
WriteLiteral("        <li");

WriteLiteral(" class=\"disabled\"");

WriteLiteral("><span>...</span></li>\r\n");

WriteLiteral("        ");

            
            #line 79 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
         Write(PagerLink((Model.TotalPages - 1).ToString(), Model.TotalPages - 1, Model.Url));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 80 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
         Write(PagerLink(Model.TotalPages.ToString(), Model.TotalPages, Model.Url));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 81 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
    }

    
            
            #line default
            #line hidden
            
            #line 83 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
                   

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 84 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
     if (Model.Current < Model.TotalPages)
    {
        
            
            #line default
            #line hidden
            
            #line 86 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
   Write(PagerLink(IlaroAdminResources.NextPage, Model.Current + 1, Model.Url, "next"));

            
            #line default
            #line hidden
            
            #line 86 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
                                                                                      
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <li");

WriteLiteral(" class=\"disabled\"");

WriteLiteral("><span>");

            
            #line 90 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
                              Write(IlaroAdminResources.NextPage);

            
            #line default
            #line hidden
WriteLiteral("</span></li>\r\n");

            
            #line 91 "..\..\Areas\IlaroAdmin\Views\Entities\_Paging.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
