#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Ilaro.Admin;
    using Ilaro.Admin.Core;
    using Ilaro.Admin.Core.Extensions;
    using Ilaro.Admin.Extensions;
    using Ilaro.Admin.Models;
    using Ilaro.Admin.Models.Paging;
    using Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/IlaroAdmin/Views/Entities/Changes.cshtml")]
    public partial class _Areas_IlaroAdmin_Views_Entities_Changes_cshtml : System.Web.Mvc.WebViewPage<EntitiesChangesModel>
    {
        public _Areas_IlaroAdmin_Views_Entities_Changes_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
  
    Layout = "~/Areas/IlaroAdmin/Views/Shared/_Layout.cshtml";
    if (Model.EntityChangesFor != null)
    {
        ViewBag.Title = Model.EntityChangesFor.Verbose.Plural + " " + IlaroAdminResources.Changes;
    }
    else
    {
        ViewBag.Title = IlaroAdminResources.Changes;
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("Breadcrumb", () => {

WriteLiteral("\r\n    <ul");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral(">\r\n        <li>");

            
            #line 18 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
       Write(Html.ActionLink(IlaroAdminResources.Index_Title, "Index", "Group", new { area = "IlaroAdmin" }, null));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

            
            #line 19 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
        
            
            #line default
            #line hidden
            
            #line 19 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
         if (Model.EntityChangesFor == null)
        {

            
            #line default
            #line hidden
WriteLiteral("            <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">");

            
            #line 21 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                          Write(IlaroAdminResources.Changes);

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

            
            #line 22 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <li>");

            
            #line 25 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
           Write(Html.ActionLink(IlaroAdminResources.Changes, "Changes", new { entityName = "", key = "" }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

            
            #line 26 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
            if (Model.Key.IsNullOrWhiteSpace())
            {

            
            #line default
            #line hidden
WriteLiteral("                <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">");

            
            #line 28 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                              Write(Model.EntityChangesFor.Name);

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

            
            #line 29 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <li>");

            
            #line 32 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
               Write(Html.ActionLink(Model.EntityChangesFor.Name, "Changes", new { entityName = Model.EntityChangesFor.Name, key = "" }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

WriteLiteral("                <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">");

            
            #line 33 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                              Write(Model.Key);

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

            
            #line 34 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
            }
        }

            
            #line default
            #line hidden
WriteLiteral("    </ul>\r\n");

});

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n    <h2");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">");

            
            #line 40 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                     Write(Model.Entity.Verbose.Plural);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n");

            
            #line 41 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
    
            
            #line default
            #line hidden
            
            #line 41 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
     if (Model.Entity.IsSearchActive)
    {
        using (Html.BeginForm("Changes", "Entities", new { area = "IlaroAdmin", page = Model.Pager.Current }, FormMethod.Get, new { @class = "pull-left col-md-3" }))
        {
            foreach (var filter in Model.ActiveFilters)
            {
                
            
            #line default
            #line hidden
            
            #line 47 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
           Write(Html.Hidden(filter.Property.Name, filter.Value));

            
            #line default
            #line hidden
            
            #line 47 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                                                                
            }
            
            
            #line default
            #line hidden
            
            #line 49 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
       Write(Html.Hidden("entityName", Model.Entity.Name));

            
            #line default
            #line hidden
            
            #line 49 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                                                         
            
            
            #line default
            #line hidden
            
            #line 50 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
       Write(Html.Hidden(Model.Configuration.PerPageRequestName, Model.TableInfo.PerPage));

            
            #line default
            #line hidden
            
            #line 50 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                                                                                         
            
            
            #line default
            #line hidden
            
            #line 51 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
       Write(Html.Hidden(Model.Configuration.OrderRequestName, Model.TableInfo.Order));

            
            #line default
            #line hidden
            
            #line 51 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                                                                                     
            
            
            #line default
            #line hidden
            
            #line 52 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
       Write(Html.Hidden(Model.Configuration.OrderDirectionRequestName, Model.TableInfo.OrderDirection));

            
            #line default
            #line hidden
            
            #line 52 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                                                                                                       

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 54 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
           Write(Html.TextBox(Model.Configuration.SearchQueryRequestName, Model.TableInfo.SearchQuery, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(">");

            
            #line 56 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                                                             Write(IlaroAdminResources.Search);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                </span>\r\n            </div>\r\n");

            
            #line 59 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(" style=\"margin-bottom:10px\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"btn-group btn-group-sm pull-right\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" class=\"btn btn-default active\"");

WriteLiteral(" id=\"make-table-large\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-th-large\"");

WriteLiteral("></span></button>\r\n        <button");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" id=\"make-table-condensed\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-th\"");

WriteLiteral("></span></button>\r\n    </div>\r\n</div>\r\n\r\n<table");

WriteLiteral(" id=\"table-entity\"");

WriteLiteral(" class=\"table table-striped table-bordered table-hover\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n");

            
            #line 73 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
            
            
            #line default
            #line hidden
            
            #line 73 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
             foreach (var column in Model.Columns)
            {

            
            #line default
            #line hidden
WriteLiteral("                <th>\r\n                    <span ");

            
            #line 76 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                     Write(Html.Condition(!string.IsNullOrEmpty(column.Description), () => "title=\"" + column.Description + "\""));

            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 77 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                   Write(Html.SortColumnLink(Model.EntityChangesFor, column, Model.Filters, Model.TableInfo.SearchQuery, Model.TableInfo.PerPage));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <i");

WriteAttribute("class", Tuple.Create(" class=\"", 3289), Tuple.Create("\"", 3346)
, Tuple.Create(Tuple.Create("", 3297), Tuple.Create("glyphicon", 3297), true)
, Tuple.Create(Tuple.Create(" ", 3306), Tuple.Create("glyphicon-chevron-", 3307), true)
            
            #line 78 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
, Tuple.Create(Tuple.Create("", 3325), Tuple.Create<System.Object, System.Int32>(column.SortDirection
            
            #line default
            #line hidden
, 3325), false)
);

WriteLiteral("></i>\r\n                    </span>\r\n                </th>\r\n");

            
            #line 81 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 85 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
        
            
            #line default
            #line hidden
            
            #line 85 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
         foreach (var row in Model.Data)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n");

            
            #line 88 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                
            
            #line default
            #line hidden
            
            #line 88 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                 foreach (var item in row.Values)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td>\r\n");

            
            #line 91 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 91 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                         if (item.Property.Name == "EntityName")
                        {
                            
            
            #line default
            #line hidden
            
            #line 93 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                       Write(Html.ActionLink(item.AsString, "Changes", new { entityName = item.AsString, key = "" }));

            
            #line default
            #line hidden
            
            #line 93 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                                                                                                                    
                        }
                        else if (item.Property.Name == "EntityKey")
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3994), Tuple.Create("\"", 4139)
            
            #line 97 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
, Tuple.Create(Tuple.Create("", 4001), Tuple.Create<System.Object, System.Int32>(Url.Action("Changes", new { entityName = row.Values.FirstOrDefault(x => x.Property.Name == "EntityName").AsString, key = item.AsString })
            
            #line default
            #line hidden
, 4001), false)
);

WriteLiteral(">");

            
            #line 97 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                                                                                                                                                                            Write(item.AsString);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 98 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                        }
                        else if (item.Property.Name == "ChangedOn")
                        {
                            
            
            #line default
            #line hidden
            
            #line 101 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                       Write(Html.ActionLink(item.AsString, "Changes", new { entityName = row.Values.FirstOrDefault(x => x.Property.Name == "EntityName").AsString, key = Model.Key, ChangedOn = ((DateTime)item.AsObject).Date.ToString("yyyy.MM.dd") }));

            
            #line default
            #line hidden
            
            #line 101 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                                                                                                                                                                                                                                                         
                        }
                        else if (item.Property.Name == "ChangedBy")
                        {
                            
            
            #line default
            #line hidden
            
            #line 105 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                       Write(Html.ActionLink(item.AsString, "Changes", new { entityName = row.Values.FirstOrDefault(x => x.Property.Name == "EntityName").AsString, key = Model.Key, ChangedBy = item.AsString }));

            
            #line default
            #line hidden
            
            #line 105 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                                                                                                                                                                                                                 
                        }
                        else if (item.Property.Name == "ChangeType")
                        {
                            
            
            #line default
            #line hidden
            
            #line 109 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                       Write(Html.ActionLink(item.AsObject.ToString(), "Changes", new { entityName = row.Values.FirstOrDefault(x => x.Property.Name == "EntityName").AsString, key = Model.Key, ChangeType = item.AsString }));

            
            #line default
            #line hidden
            
            #line 109 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                                                                                                                                                                                                                             
                        }
                        else
                        {
                            
            
            #line default
            #line hidden
            
            #line 113 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                       Write(Html.DisplayFor(m => item, item.Property.Template.Display));

            
            #line default
            #line hidden
            
            #line 113 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                                                                                       
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </td>\r\n");

            
            #line 116 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n");

            
            #line 118 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>\r\n\r\n<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(" style=\"margin-right:10px\"");

WriteLiteral(">\r\n");

            
            #line 124 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
        
            
            #line default
            #line hidden
            
            #line 124 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
         using (Html.BeginForm("Changes", "Entities", new { area = "IlaroAdmin", page = Model.Pager.Current }, FormMethod.Get, new { @class = "form-inline" }))
        {
            foreach (var filter in Model.ActiveFilters)
            {
                
            
            #line default
            #line hidden
            
            #line 128 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
           Write(Html.Hidden(filter.Property.Name, filter.Value));

            
            #line default
            #line hidden
            
            #line 128 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                                                                
            }
            
            
            #line default
            #line hidden
            
            #line 130 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
       Write(Html.Hidden("entityName", Model.Entity.Name));

            
            #line default
            #line hidden
            
            #line 130 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                                                         
            
            
            #line default
            #line hidden
            
            #line 131 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
       Write(Html.Hidden(Model.Configuration.SearchQueryRequestName, Model.TableInfo.SearchQuery));

            
            #line default
            #line hidden
            
            #line 131 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                                                                                                 
            
            
            #line default
            #line hidden
            
            #line 132 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
       Write(Html.Hidden(Model.Configuration.OrderRequestName, Model.TableInfo.Order));

            
            #line default
            #line hidden
            
            #line 132 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                                                                                     
            
            
            #line default
            #line hidden
            
            #line 133 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
       Write(Html.Hidden(Model.Configuration.OrderDirectionRequestName, Model.TableInfo.OrderDirection));

            
            #line default
            #line hidden
            
            #line 133 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                                                                                                       

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteAttribute("for", Tuple.Create(" for=\"", 6332), Tuple.Create("\"", 6377)
            
            #line 135 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
, Tuple.Create(Tuple.Create("", 6338), Tuple.Create<System.Object, System.Int32>(Model.Configuration.PerPageRequestName
            
            #line default
            #line hidden
, 6338), false)
);

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">");

            
            #line 135 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                                                                                      Write(IlaroAdminResources.OnPage);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n");

WriteLiteral("                ");

            
            #line 136 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
           Write(Html.DropDownList(Model.Configuration.PageRequestName,
                 new SelectList(new Dictionary<int, int> { { 5, 5 }, { 10, 10 }, { 15, 15 }, { 20, 20 }, { 25, 25 }, { 50, 50 }, { 100, 100 } }, "Key", "Value", Model.TableInfo.PerPage),
                 new Dictionary<string, object> { { "class", "autoPostBack form-control" }, { "id", "per-page-entity" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

            
            #line 140 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(" style=\"margin-right:10px\"");

WriteLiteral(">\r\n");

            
            #line 144 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
        
            
            #line default
            #line hidden
            
            #line 144 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
          Html.RenderPartial("_Paging", Model.Pager);
            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(" style=\"line-height:29px\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 148 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
   Write(IlaroAdminResources.Founded);

            
            #line default
            #line hidden
WriteLiteral(" <strong>");

            
            #line 148 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                                        Write(Model.Pager.TotalItems);

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("Sidebar", () => {

WriteLiteral("\r\n");

            
            #line 154 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
    
            
            #line default
            #line hidden
            
            #line 154 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
     if (Model.Filters.Count > 0)
    {

            
            #line default
            #line hidden
WriteLiteral("        <h2>");

            
            #line 156 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
       Write(IlaroAdminResources.Filters);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n");

WriteLiteral("        <ul");

WriteLiteral(" class=\"nav nav-list\"");

WriteLiteral(">\r\n            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 7311), Tuple.Create("\"", 7406)
            
            #line 158 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
, Tuple.Create(Tuple.Create("", 7318), Tuple.Create<System.Object, System.Int32>(Url.Action("Changes", new {entityName = Model.Entity.Name, page = Model.Pager.Current})
            
            #line default
            #line hidden
, 7318), false)
);

WriteLiteral(">");

            
            #line 158 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
                                                                                                              Write(IlaroAdminResources.RemoveFilters);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 159 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
            
            
            #line default
            #line hidden
            
            #line 159 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
             foreach (var filter in Model.Filters)
            {
                Html.RenderPartial("_Filter", filter);
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n");

            
            #line 164 "..\..\Areas\IlaroAdmin\Views\Entities\Changes.cshtml"
    }

            
            #line default
            #line hidden
});

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        $().ready(function () {
            $('#make-table-large').click(function () {
                var $this = $(this).addClass('active').siblings().removeClass('active');
                $('#table-entity').removeClass('table-condensed');
                $('#pagination-entity').removeClass('pagination-sm');
                $('#per-page-entity').removeClass('select-sm');
            });
            $('#make-table-condensed').click(function () {
                var $this = $(this).addClass('active').siblings().removeClass('active');
                $('#table-entity').addClass('table-condensed');
                $('#pagination-entity').addClass('pagination-sm');
                $('#per-page-entity').addClass('select-sm');
            });
        });
    </script>
");

});

        }
    }
}
#pragma warning restore 1591
