#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Ilaro.Admin;
    using Ilaro.Admin.Core;
    using Ilaro.Admin.Core.Extensions;
    using Ilaro.Admin.Core.Models;
    using Ilaro.Admin.Core.Models.Paging;
    using Ilaro.Admin.Extensions;
    using Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/IlaroAdmin/Views/Shared/DisplayTemplates/ImagePartial.cshtml")]
    public partial class _Areas_IlaroAdmin_Views_Shared_DisplayTemplates_ImagePartial_cshtml_ : System.Web.Mvc.WebViewPage<PropertyValue>
    {
        public _Areas_IlaroAdmin_Views_Shared_DisplayTemplates_ImagePartial_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\IlaroAdmin\Views\Shared\DisplayTemplates\ImagePartial.cshtml"
  
    if (Model.Raw == null)
    {
        return;
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<a");

WriteAttribute("href", Tuple.Create(" href=\"", 92), Tuple.Create("\"", 126)
            
            #line 9 "..\..\Areas\IlaroAdmin\Views\Shared\DisplayTemplates\ImagePartial.cshtml"
, Tuple.Create(Tuple.Create("", 99), Tuple.Create<System.Object, System.Int32>(Url.GetImageBigPath(Model)
            
            #line default
            #line hidden
, 99), false)
);

WriteLiteral(" class=\"open-modal\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 151), Tuple.Create("\"", 184)
            
            #line 9 "..\..\Areas\IlaroAdmin\Views\Shared\DisplayTemplates\ImagePartial.cshtml"
, Tuple.Create(Tuple.Create("", 157), Tuple.Create<System.Object, System.Int32>(Url.GetImageMinPath(Model)
            
            #line default
            #line hidden
, 157), false)
);

WriteLiteral(" class=\"img-thumbnail\"");

WriteAttribute("alt", Tuple.Create(" alt=\"", 207), Tuple.Create("\"", 228)
            
            #line 9 "..\..\Areas\IlaroAdmin\Views\Shared\DisplayTemplates\ImagePartial.cshtml"
                                            , Tuple.Create(Tuple.Create("", 213), Tuple.Create<System.Object, System.Int32>(Model.AsString
            
            #line default
            #line hidden
, 213), false)
);

WriteLiteral(" /></a>\r\n");

        }
    }
}
#pragma warning restore 1591
