using System;
using System.CodeDom.Compiler;
using System.Web.Mvc;
using System.Web.Mvc.Html;
using System.Web.WebPages;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    [GeneratedCode("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Areas/IlaroAdmin/Views/Shared/_Layout.cshtml")]
    public partial class _Areas_IlaroAdmin_Views_Shared__Layout_cshtml : WebViewPage<dynamic>
    {
        public _Areas_IlaroAdmin_Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\IlaroAdmin\Views\Shared\_Layout.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <title>");

            
            #line 8 "..\..\Areas\IlaroAdmin\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 210), Tuple.Create("\"", 244)
, Tuple.Create(Tuple.Create("", 217), Tuple.Create<Object, Int32>(Href("~/ira/css/bootstrap_min_css")
, 217), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 276), Tuple.Create("\"", 313)
, Tuple.Create(Tuple.Create("", 283), Tuple.Create<Object, Int32>(Href("~/ira/css/font-awesome_min_css")
, 283), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 345), Tuple.Create("\"", 394)
, Tuple.Create(Tuple.Create("", 352), Tuple.Create<Object, Int32>(Href("~/ira/css/bootstrap-datetimepicker_min_css")
, 352), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 426), Tuple.Create("\"", 457)
, Tuple.Create(Tuple.Create("", 433), Tuple.Create<Object, Int32>(Href("~/ira/css/chosen_min_css")
, 433), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 489), Tuple.Create("\"", 528)
, Tuple.Create(Tuple.Create("", 496), Tuple.Create<Object, Int32>(Href("~/ira/css/bootstrap-spinedit_css")
, 496), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 560), Tuple.Create("\"", 603)
, Tuple.Create(Tuple.Create("", 567), Tuple.Create<Object, Int32>(Href("~/ira/css/bootstrap-markdown_min_css")
, 567), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 635), Tuple.Create("\"", 666)
, Tuple.Create(Tuple.Create("", 642), Tuple.Create<Object, Int32>(Href("~/ira/css/summernote_css")
, 642), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 698), Tuple.Create("\"", 744)
, Tuple.Create(Tuple.Create("", 705), Tuple.Create<Object, Int32>(Href("~/ira/css/bootstrap-duallistbox_min_css")
, 705), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 776), Tuple.Create("\"", 801)
, Tuple.Create(Tuple.Create("", 783), Tuple.Create<Object, Int32>(Href("~/ira/css/site_css")
, 783), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 837), Tuple.Create("\"", 875)
, Tuple.Create(Tuple.Create("", 843), Tuple.Create<Object, Int32>(Href("~/ira/Script/jquery-2_1_0_min_js")
, 843), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

WriteLiteral("    ");

            
            #line 21 "..\..\Areas\IlaroAdmin\Views\Shared\_Layout.cshtml"
Write(RenderSection("Header", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body>\r\n    <div");

WriteLiteral(" class=\"navbar navbar-default navbar-static-top\"");

WriteLiteral(" role=\"navigation\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n            <h1>");

            
            #line 26 "..\..\Areas\IlaroAdmin\Views\Shared\_Layout.cshtml"
           Write(Html.ActionLink("Admin", "Index", "Group", new { area = "IlaroAdmin" }, new { @class = "navbar-brand" }));

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n");

            
            #line 28 "..\..\Areas\IlaroAdmin\Views\Shared\_Layout.cshtml"
            
            
            #line default
            #line hidden
            
            #line 28 "..\..\Areas\IlaroAdmin\Views\Shared\_Layout.cshtml"
              Html.RenderPartial("_UserInfo");
            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"breadcrumb-container\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 34 "..\..\Areas\IlaroAdmin\Views\Shared\_Layout.cshtml"
       Write(RenderSection("Breadcrumb", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n");

            
            #line 36 "..\..\Areas\IlaroAdmin\Views\Shared\_Layout.cshtml"
        
            
            #line default
            #line hidden
            
            #line 36 "..\..\Areas\IlaroAdmin\Views\Shared\_Layout.cshtml"
          Html.RenderAction("Messages", "Shared", new { area = "IlaroAdmin" });
            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 39 "..\..\Areas\IlaroAdmin\Views\Shared\_Layout.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 42 "..\..\Areas\IlaroAdmin\Views\Shared\_Layout.cshtml"
           Write(RenderSection("Sidebar", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <hr>\r\n        <footer>\r\n           " +
" <p>© <a");

WriteLiteral(" href=\"https://github.com/rgonek/Ilaro.Admin\"");

WriteLiteral(">Ilaro.Admin</a> ");

            
            #line 47 "..\..\Areas\IlaroAdmin\Views\Shared\_Layout.cshtml"
                                                                            Write(DateTime.Now.ToString("yyyy"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n        </footer>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" id=\"modal\"");

WriteLiteral(" class=\"modal hide fade\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n            <img");

WriteLiteral(" id=\"modal-image\"");

WriteLiteral(" />\r\n        </div>\r\n    </div>\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2094), Tuple.Create("\"", 2135)
, Tuple.Create(Tuple.Create("", 2100), Tuple.Create<Object, Int32>(Href("~/ira/Script/jquery_validate_min_js")
, 2100), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2159), Tuple.Create("\"", 2212)
, Tuple.Create(Tuple.Create("", 2165), Tuple.Create<Object, Int32>(Href("~/ira/Script/jquery_validate_unobtrusive_min_js")
, 2165), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2236), Tuple.Create("\"", 2275)
, Tuple.Create(Tuple.Create("", 2242), Tuple.Create<Object, Int32>(Href("~/ira/Script/chosen_jquery_min_js")
, 2242), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2299), Tuple.Create("\"", 2331)
, Tuple.Create(Tuple.Create("", 2305), Tuple.Create<Object, Int32>(Href("~/ira/Script/moment_min_js")
, 2305), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2355), Tuple.Create("\"", 2405)
, Tuple.Create(Tuple.Create("", 2361), Tuple.Create<Object, Int32>(Href("~/ira/Script/bootstrap-datetimepicker_min_js")
, 2361), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2429), Tuple.Create("\"", 2464)
, Tuple.Create(Tuple.Create("", 2435), Tuple.Create<Object, Int32>(Href("~/ira/Script/bootstrap_min_js")
, 2435), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2488), Tuple.Create("\"", 2528)
, Tuple.Create(Tuple.Create("", 2494), Tuple.Create<Object, Int32>(Href("~/ira/Script/bootstrap-spinedit_js")
, 2494), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2552), Tuple.Create("\"", 2584)
, Tuple.Create(Tuple.Create("", 2558), Tuple.Create<Object, Int32>(Href("~/ira/Script/marked_min_js")
, 2558), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2608), Tuple.Create("\"", 2648)
, Tuple.Create(Tuple.Create("", 2614), Tuple.Create<Object, Int32>(Href("~/ira/Script/bootstrap-markdown_js")
, 2614), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2672), Tuple.Create("\"", 2708)
, Tuple.Create(Tuple.Create("", 2678), Tuple.Create<Object, Int32>(Href("~/ira/Script/summernote_min_js")
, 2678), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2732), Tuple.Create("\"", 2786)
, Tuple.Create(Tuple.Create("", 2738), Tuple.Create<Object, Int32>(Href("~/ira/Script/jquery_bootstrap-duallistbox_min_js")
, 2738), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2810), Tuple.Create("\"", 2837)
, Tuple.Create(Tuple.Create("", 2816), Tuple.Create<Object, Int32>(Href("~/ira/Script/ilaro_js")
, 2816), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2861), Tuple.Create("\"", 2903)
, Tuple.Create(Tuple.Create("", 2867), Tuple.Create<Object, Int32>(Href("~/ira/Script/bootstrap_file-input_js")
, 2867), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    ");

            
            #line 70 "..\..\Areas\IlaroAdmin\Views\Shared\_Layout.cshtml"
Write(RenderSection("Scripts", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
