#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Ilaro.Admin;
    using Ilaro.Admin.Core;
    using Ilaro.Admin.Extensions;
    using Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/IlaroAdmin/Views/Shared/_Messages.cshtml")]
    public partial class _Areas_IlaroAdmin_Views_Shared__Messages_cshtml : System.Web.Mvc.WebViewPage<Notificator>
    {
        public _Areas_IlaroAdmin_Views_Shared__Messages_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"messages\"");

WriteLiteral(" id=\"messages\"");

WriteLiteral(">\r\n");

            
            #line 4 "..\..\Areas\IlaroAdmin\Views\Shared\_Messages.cshtml"
    
            
            #line default
            #line hidden
            
            #line 4 "..\..\Areas\IlaroAdmin\Views\Shared\_Messages.cshtml"
     foreach (var kvp in Model.Messages)
    {
        if (kvp.Value.Count > 0)
        {
            while (kvp.Value.Count > 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteAttribute("class", Tuple.Create(" class=\"", 230), Tuple.Create("\"", 299)
, Tuple.Create(Tuple.Create("", 238), Tuple.Create("alert", 238), true)
, Tuple.Create(Tuple.Create(" ", 243), Tuple.Create("alert-block", 244), true)
, Tuple.Create(Tuple.Create(" ", 255), Tuple.Create("alert-", 256), true)
            
            #line 10 "..\..\Areas\IlaroAdmin\Views\Shared\_Messages.cshtml"
, Tuple.Create(Tuple.Create("", 262), Tuple.Create<System.Object, System.Int32>(kvp.Key.ToString().ToLower()
            
            #line default
            #line hidden
, 262), false)
, Tuple.Create(Tuple.Create(" ", 291), Tuple.Create("fade", 292), true)
, Tuple.Create(Tuple.Create(" ", 296), Tuple.Create("in", 297), true)
);

WriteLiteral("><button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"alert\"");

WriteLiteral(">&times;</button>");

            
            #line 10 "..\..\Areas\IlaroAdmin\Views\Shared\_Messages.cshtml"
                                                                                                                                                               Write(Html.Raw(kvp.Value.Dequeue()));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 11 "..\..\Areas\IlaroAdmin\Views\Shared\_Messages.cshtml"
            }
        }
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

        }
    }
}
#pragma warning restore 1591
