#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Ilaro.Admin.Commons.Paging;
    using Ilaro.Admin.Core;
    using Ilaro.Admin.Extensions;
    
    #line 1 "..\..\Views\IlaroAdmin\_GroupPartial.cshtml"
    using Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/IlaroAdmin/_GroupPartial.cshtml")]
    public partial class _Views_IlaroAdmin__GroupPartial_cshtml : System.Web.Mvc.WebViewPage<Ilaro.Admin.ViewModels.EntityGroupViewModel>
    {
        public _Views_IlaroAdmin__GroupPartial_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\IlaroAdmin\_GroupPartial.cshtml"
 if (!Model.Name.IsNullOrEmpty())
{

            
            #line default
            #line hidden
WriteLiteral("    <h3>");

            
            #line 6 "..\..\Views\IlaroAdmin\_GroupPartial.cshtml"
   Write(Html.ActionLink(Model.Name, "Group", new { groupName = Model.Name }));

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n");

            
            #line 7 "..\..\Views\IlaroAdmin\_GroupPartial.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<table");

WriteLiteral(" class=\"table table-striped table-bordered table-hover\"");

WriteLiteral(">\r\n    <tbody>\r\n");

            
            #line 10 "..\..\Views\IlaroAdmin\_GroupPartial.cshtml"
        
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\IlaroAdmin\_GroupPartial.cshtml"
         foreach (var entity in Model.Entities)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td");

WriteLiteral(" class=\"max-width\"");

WriteLiteral(">");

            
            #line 13 "..\..\Views\IlaroAdmin\_GroupPartial.cshtml"
                                 Write(Html.ActionLink(entity.Verbose.Plural, "List", new { entityName = entity.Name }));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>\r\n");

            
            #line 15 "..\..\Views\IlaroAdmin\_GroupPartial.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\IlaroAdmin\_GroupPartial.cshtml"
                     if (entity.CanAdd)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 590), Tuple.Create("\"", 652)
            
            #line 17 "..\..\Views\IlaroAdmin\_GroupPartial.cshtml"
, Tuple.Create(Tuple.Create("", 597), Tuple.Create<System.Object, System.Int32>(Url.Action("Create", new { entityName = entity.Name })
            
            #line default
            #line hidden
, 597), false)
);

WriteLiteral(" class=\"btn btn-xs btn-link\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphglyphicon glyphicon-plus\"");

WriteLiteral("></span> ");

            
            #line 17 "..\..\Views\IlaroAdmin\_GroupPartial.cshtml"
                                                                                                                                                                               Write(IlaroAdminResources.Add);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 18 "..\..\Views\IlaroAdmin\_GroupPartial.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n            </tr>\r\n");

            
            #line 21 "..\..\Views\IlaroAdmin\_GroupPartial.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
