#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilaro.Admin.Views.IlaroAdmin
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Ilaro.Admin.Commons.Paging;
    using Ilaro.Admin.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/IlaroAdmin/_GroupPartial.cshtml")]
    public partial class GroupPartial : System.Web.Mvc.WebViewPage<Ilaro.Admin.ViewModels.EntityGroupViewModel>
    {
        public GroupPartial()
        {
        }
        public override void Execute()
        {
WriteLiteral("<li");

WriteLiteral(" class=\"span4\"");

WriteLiteral(">\r\n    <h3>");

            
            #line 4 "..\..\Views\IlaroAdmin\_GroupPartial.cshtml"
   Write(Html.ActionLink(Model.Name, "Group", new { groupName =  Model.Name }));

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n    <table");

WriteLiteral(" class=\"table table-striped table-bordered table-hover\"");

WriteLiteral(">\r\n        <tbody>\r\n");

            
            #line 7 "..\..\Views\IlaroAdmin\_GroupPartial.cshtml"
            
            
            #line default
            #line hidden
            
            #line 7 "..\..\Views\IlaroAdmin\_GroupPartial.cshtml"
             foreach (var entity in Model.Entities) 
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td");

WriteLiteral(" class=\"max-width\"");

WriteLiteral(">");

            
            #line 10 "..\..\Views\IlaroAdmin\_GroupPartial.cshtml"
                                     Write(Html.ActionLink(entity.Plural, "Details", new { entityName = entity.Name }));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>\r\n");

            
            #line 12 "..\..\Views\IlaroAdmin\_GroupPartial.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\IlaroAdmin\_GroupPartial.cshtml"
                         if (entity.CanAdd) 
                        { 

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 597), Tuple.Create("\"", 659)
            
            #line 14 "..\..\Views\IlaroAdmin\_GroupPartial.cshtml"
, Tuple.Create(Tuple.Create("", 604), Tuple.Create<System.Object, System.Int32>(Url.Action("Create", new { entityName = entity.Name })
            
            #line default
            #line hidden
, 604), false)
);

WriteLiteral(" class=\"btn btn-mini btn-link\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-plus\"");

WriteLiteral("></i> ");

            
            #line 14 "..\..\Views\IlaroAdmin\_GroupPartial.cshtml"
                                                                                                                                             Write(Resources.IlaroAdminResources.Add);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 15 "..\..\Views\IlaroAdmin\_GroupPartial.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </td>\r\n                </tr>\r\n");

            
            #line 18 "..\..\Views\IlaroAdmin\_GroupPartial.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n</li>");

        }
    }
}
#pragma warning restore 1591
