#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Ilaro.Admin.Commons.Paging;
    using Ilaro.Admin.Core;
    using Ilaro.Admin.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/IlaroAdmin/_Messages.cshtml")]
    public partial class _Views_IlaroAdmin__Messages_cshtml : System.Web.Mvc.WebViewPage<Ilaro.Admin.Commons.Notificator.Notificator>
    {
        public _Views_IlaroAdmin__Messages_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"messages\"");

WriteLiteral(" id=\"messages\"");

WriteLiteral(">\r\n");

            
            #line 4 "..\..\Views\IlaroAdmin\_Messages.cshtml"
    
            
            #line default
            #line hidden
            
            #line 4 "..\..\Views\IlaroAdmin\_Messages.cshtml"
     foreach (var kvp in Model.Messages)
    {
        if (kvp.Value.Count > 0)
        {
            while (kvp.Value.Count > 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteAttribute("class", Tuple.Create(" class=\"", 262), Tuple.Create("\"", 331)
, Tuple.Create(Tuple.Create("", 270), Tuple.Create("alert", 270), true)
, Tuple.Create(Tuple.Create(" ", 275), Tuple.Create("alert-block", 276), true)
, Tuple.Create(Tuple.Create(" ", 287), Tuple.Create("alert-", 288), true)
            
            #line 10 "..\..\Views\IlaroAdmin\_Messages.cshtml"
, Tuple.Create(Tuple.Create("", 294), Tuple.Create<System.Object, System.Int32>(kvp.Key.ToString().ToLower()
            
            #line default
            #line hidden
, 294), false)
, Tuple.Create(Tuple.Create(" ", 323), Tuple.Create("fade", 324), true)
, Tuple.Create(Tuple.Create(" ", 328), Tuple.Create("in", 329), true)
);

WriteLiteral("><button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"alert\"");

WriteLiteral(">&times;</button>");

            
            #line 10 "..\..\Views\IlaroAdmin\_Messages.cshtml"
                                                                                                                                                               Write(Html.Raw(kvp.Value.Dequeue()));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 11 "..\..\Views\IlaroAdmin\_Messages.cshtml"
            }
        }
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
