using System;
using System.CodeDom.Compiler;
using System.Web.Mvc;
using System.Web.WebPages;
using Ilaro.Admin.ViewModels;
using Resources;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilaro.Admin.Views.IlaroAdmin
{
    [GeneratedCode("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Views/IlaroAdmin/_Paging.cshtml")]
    public partial class Paging : WebViewPage<PagerInfo>
    {

#line 93 "..\..\Views\IlaroAdmin\_Paging.cshtml"
public HelperResult PagerLink(string linkText, int pageNumber, string url, string rel = "", string @classes = "")
{
#line default
#line hidden
return new HelperResult(__razor_helper_writer => {

#line 94 "..\..\Views\IlaroAdmin\_Paging.cshtml"
 
    url = string.Format(url, pageNumber);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <li");

WriteAttributeTo(__razor_helper_writer, "class", Tuple.Create(" class=\"", 2908), Tuple.Create("\"", 2924)

#line 96 "..\..\Views\IlaroAdmin\_Paging.cshtml"
, Tuple.Create(Tuple.Create("", 2916), Tuple.Create<Object, Int32>(classes

#line default
#line hidden
, 2916), false)
);

WriteLiteralTo(__razor_helper_writer, "><a");

WriteAttributeTo(__razor_helper_writer, "href", Tuple.Create(" href=\"", 2928), Tuple.Create("\"", 2939)

#line 96 "..\..\Views\IlaroAdmin\_Paging.cshtml"
, Tuple.Create(Tuple.Create("", 2935), Tuple.Create<Object, Int32>(url

#line default
#line hidden
, 2935), false)
);

WriteAttributeTo(__razor_helper_writer, "rel", Tuple.Create(" rel=\"", 2940), Tuple.Create("\"", 2950)

#line 96 "..\..\Views\IlaroAdmin\_Paging.cshtml"
, Tuple.Create(Tuple.Create("", 2946), Tuple.Create<Object, Int32>(rel

#line default
#line hidden
, 2946), false)
);

WriteLiteralTo(__razor_helper_writer, ">");


#line 96 "..\..\Views\IlaroAdmin\_Paging.cshtml"
                     WriteTo(__razor_helper_writer, linkText);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</a></li>\r\n");


#line 97 "..\..\Views\IlaroAdmin\_Paging.cshtml"


#line default
#line hidden
});

#line 97 "..\..\Views\IlaroAdmin\_Paging.cshtml"
}
#line default
#line hidden

        public Paging()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 10 "..\..\Views\IlaroAdmin\_Paging.cshtml"
 if (Model.TotalPages <= 1)
{
    return;
}

            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\IlaroAdmin\_Paging.cshtml"
  var nrOfPagesToDisplay = 10;
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<ul");

WriteLiteral(" id=\"pagination-entity\"");

WriteLiteral(" class=\"pagination\"");

WriteLiteral(">\r\n");

            
            #line 17 "..\..\Views\IlaroAdmin\_Paging.cshtml"
    
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\IlaroAdmin\_Paging.cshtml"
      
        // Make some calculation
        var start = 1;
        var end = Model.TotalPages;
        if (Model.TotalPages > nrOfPagesToDisplay)
        {
            var middle = (int)Math.Ceiling(nrOfPagesToDisplay / 2d) - 1;
            var below = (Model.Current - middle);
            var above = (Model.Current + middle);

            if (below < 4)
            {
                above = nrOfPagesToDisplay;
                below = 1;
            }
            else if (above > (Model.TotalPages - 4))
            {
                above = Model.TotalPages;
                below = (Model.TotalPages - nrOfPagesToDisplay);
            }

            start = below;
            end = above;
        }
    
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    ");

WriteLiteral("\r\n");

            
            #line 44 "..\..\Views\IlaroAdmin\_Paging.cshtml"
    
            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\IlaroAdmin\_Paging.cshtml"
     if (Model.Current > 1)
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 46 "..\..\Views\IlaroAdmin\_Paging.cshtml"
         Write(PagerLink(IlaroAdminResources.PreviousPage, Model.Current - 1, Model.Url, "prev"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 47 "..\..\Views\IlaroAdmin\_Paging.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <li");

WriteLiteral(" class=\"disabled\"");

WriteLiteral("><span>");

            
            #line 50 "..\..\Views\IlaroAdmin\_Paging.cshtml"
                              Write(IlaroAdminResources.PreviousPage);

            
            #line default
            #line hidden
WriteLiteral("</span></li>\r\n");

            
            #line 51 "..\..\Views\IlaroAdmin\_Paging.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

WriteLiteral("\r\n");

            
            #line 54 "..\..\Views\IlaroAdmin\_Paging.cshtml"
    
            
            #line default
            #line hidden
            
            #line 54 "..\..\Views\IlaroAdmin\_Paging.cshtml"
     if (start > 3)
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 56 "..\..\Views\IlaroAdmin\_Paging.cshtml"
         Write(PagerLink("1", 1, Model.Url));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 57 "..\..\Views\IlaroAdmin\_Paging.cshtml"
         Write(PagerLink("2", 2, Model.Url));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        <li");

WriteLiteral(" class=\"disabled\"");

WriteLiteral("><span>...</span></li>\r\n");

            
            #line 59 "..\..\Views\IlaroAdmin\_Paging.cshtml"
    }

    
            
            #line default
            #line hidden
            
            #line 61 "..\..\Views\IlaroAdmin\_Paging.cshtml"
                      

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 62 "..\..\Views\IlaroAdmin\_Paging.cshtml"
     for (var i = start; i <= end; i++)
    {
        if (i == Model.Current || (Model.Current <= 0 && i == 0))
        {

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 66 "..\..\Views\IlaroAdmin\_Paging.cshtml"
             Write(PagerLink(i.ToString(), i, Model.Url, "", "active"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 67 "..\..\Views\IlaroAdmin\_Paging.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 70 "..\..\Views\IlaroAdmin\_Paging.cshtml"
             Write(PagerLink(i.ToString(), i, Model.Url));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 71 "..\..\Views\IlaroAdmin\_Paging.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

WriteLiteral("\r\n");

            
            #line 75 "..\..\Views\IlaroAdmin\_Paging.cshtml"
    
            
            #line default
            #line hidden
            
            #line 75 "..\..\Views\IlaroAdmin\_Paging.cshtml"
     if (end < (Model.TotalPages - 3))
    {

            
            #line default
            #line hidden
WriteLiteral("        <li");

WriteLiteral(" class=\"disabled\"");

WriteLiteral("><span>...</span></li>\r\n");

WriteLiteral("        ");

            
            #line 78 "..\..\Views\IlaroAdmin\_Paging.cshtml"
         Write(PagerLink((Model.TotalPages - 1).ToString(), Model.TotalPages - 1, Model.Url));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 79 "..\..\Views\IlaroAdmin\_Paging.cshtml"
         Write(PagerLink(Model.TotalPages.ToString(), Model.TotalPages, Model.Url));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 80 "..\..\Views\IlaroAdmin\_Paging.cshtml"
    }

    
            
            #line default
            #line hidden
            
            #line 82 "..\..\Views\IlaroAdmin\_Paging.cshtml"
                   

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 83 "..\..\Views\IlaroAdmin\_Paging.cshtml"
     if (Model.Current < Model.TotalPages)
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 85 "..\..\Views\IlaroAdmin\_Paging.cshtml"
         Write(PagerLink(IlaroAdminResources.NextPage, Model.Current + 1, Model.Url, "next"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 86 "..\..\Views\IlaroAdmin\_Paging.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <li");

WriteLiteral(" class=\"disabled\"");

WriteLiteral("><span>");

            
            #line 89 "..\..\Views\IlaroAdmin\_Paging.cshtml"
                              Write(IlaroAdminResources.NextPage);

            
            #line default
            #line hidden
WriteLiteral("</span></li>\r\n");

            
            #line 90 "..\..\Views\IlaroAdmin\_Paging.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
