#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Ilaro.Admin.Commons.Paging;
    using Ilaro.Admin.Core;
    using Ilaro.Admin.Extensions;
    
    #line 1 "..\..\Views\IlaroAdmin\Create.cshtml"
    using Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/IlaroAdmin/Create.cshtml")]
    public partial class _Views_IlaroAdmin_Create_cshtml : System.Web.Mvc.WebViewPage<Ilaro.Admin.ViewModels.CreateViewModel>
    {
        public _Views_IlaroAdmin_Create_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\IlaroAdmin\Create.cshtml"
  
	if (ViewBag.IsAjaxRequest)
	{
		Layout = null;
	}
	else
	{
		Layout = "~/Views/IlaroAdmin/_Layout.cshtml";
	}
	ViewBag.Title = string.Format(IlaroAdminResources.Create_Title, Model.Entity.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("Breadcrumb", () => {

WriteLiteral("\r\n\t<ul");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral(">\r\n\t\t<li>");

            
            #line 19 "..\..\Views\IlaroAdmin\Create.cshtml"
 Write(Html.ActionLink(IlaroAdminResources.Index_Title, "Index"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n\t\t<li>");

            
            #line 20 "..\..\Views\IlaroAdmin\Create.cshtml"
 Write(Html.ActionLink(Model.Entity.Verbose.Group, "Group", new { groupName = Model.Entity.Verbose.Group }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n\t\t<li>");

            
            #line 21 "..\..\Views\IlaroAdmin\Create.cshtml"
 Write(Html.ActionLink(Model.Entity.Verbose.Plural, "List", new { entityName = Model.Entity.Name }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n\t\t<li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">");

            
            #line 22 "..\..\Views\IlaroAdmin\Create.cshtml"
                Write(string.Format(IlaroAdminResources.Create_Title, Model.Entity.Name));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n\t</ul>\r\n");

});

WriteLiteral("\r\n<h2>");

            
            #line 26 "..\..\Views\IlaroAdmin\Create.cshtml"
Write(Model.Entity.Verbose.Singular);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n\r\n");

            
            #line 28 "..\..\Views\IlaroAdmin\Create.cshtml"
 using (Html.BeginForm("Create", "IlaroAdmin", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", role = "form" }))
{
	
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\IlaroAdmin\Create.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\IlaroAdmin\Create.cshtml"
                         
	
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\IlaroAdmin\Create.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\IlaroAdmin\Create.cshtml"
                              

	if (Model.PropertiesGroups.Count > 1)
	{
		foreach (var group in Model.PropertiesGroups)
		{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<fieldset>\r\n\t\t\t\t<legend>");

            
            #line 38 "..\..\Views\IlaroAdmin\Create.cshtml"
       Write(group.GroupName);

            
            #line default
            #line hidden
WriteLiteral(" <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn pull-right\"");

WriteLiteral("><i");

WriteAttribute("class", Tuple.Create(" class=\"", 1176), Tuple.Create("\"", 1287)
            
            #line 38 "..\..\Views\IlaroAdmin\Create.cshtml"
    , Tuple.Create(Tuple.Create("", 1184), Tuple.Create<System.Object, System.Int32>(Html.Condition(group.IsCollapsed, () => "glyphicon glyphicon-plus", () => "glyphicon glyphicon-minus")
            
            #line default
            #line hidden
, 1184), false)
);

WriteLiteral("></i></button></legend>\r\n\t\t\t\t<div");

WriteAttribute("class", Tuple.Create(" class=\"", 1321), Tuple.Create("\"", 1384)
, Tuple.Create(Tuple.Create("", 1329), Tuple.Create("fields", 1329), true)
            
            #line 39 "..\..\Views\IlaroAdmin\Create.cshtml"
, Tuple.Create(Tuple.Create(" ", 1335), Tuple.Create<System.Object, System.Int32>(Html.Condition(group.IsCollapsed, () => "hide")
            
            #line default
            #line hidden
, 1336), false)
);

WriteLiteral(">\r\n");

            
            #line 40 "..\..\Views\IlaroAdmin\Create.cshtml"
					
            
            #line default
            #line hidden
            
            #line 40 "..\..\Views\IlaroAdmin\Create.cshtml"
      foreach (var property in group.Properties)
					{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 43 "..\..\Views\IlaroAdmin\Create.cshtml"
  Write(Html.EditorFor(m => property, property.Template.Editor));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 44 "..\..\Views\IlaroAdmin\Create.cshtml"
							
            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\IlaroAdmin\Create.cshtml"
        if (property.IsForeignKey)
							{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 1599), Tuple.Create("\"", 1677)
            
            #line 46 "..\..\Views\IlaroAdmin\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1606), Tuple.Create<System.Object, System.Int32>(Url.Action("Create", new { entityName = property.ForeignEntity.Name })
            
            #line default
            #line hidden
, 1606), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" class=\"btn btn-primary create-foreign\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-plus\"");

WriteLiteral("></span></a>\r\n");

            
            #line 47 "..\..\Views\IlaroAdmin\Create.cshtml"
							}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t</div>\r\n");

            
            #line 49 "..\..\Views\IlaroAdmin\Create.cshtml"
					}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t</div>\r\n\t\t\t</fieldset>\r\n");

            
            #line 52 "..\..\Views\IlaroAdmin\Create.cshtml"
		}
	}
	else if (Model.PropertiesGroups.Count == 1)
	{
		foreach (var property in Model.PropertiesGroups[0].Properties)
		{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 59 "..\..\Views\IlaroAdmin\Create.cshtml"
Write(Html.EditorFor(m => property, property.Template.Editor));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 60 "..\..\Views\IlaroAdmin\Create.cshtml"
				
            
            #line default
            #line hidden
            
            #line 60 "..\..\Views\IlaroAdmin\Create.cshtml"
     if (property.IsForeignKey)
				{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 2114), Tuple.Create("\"", 2192)
            
            #line 62 "..\..\Views\IlaroAdmin\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2121), Tuple.Create<System.Object, System.Int32>(Url.Action("Create", new { entityName = property.ForeignEntity.Name })
            
            #line default
            #line hidden
, 2121), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" class=\"btn btn-primary create-foreign\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-plus\"");

WriteLiteral("></span></a>\r\n");

            
            #line 63 "..\..\Views\IlaroAdmin\Create.cshtml"
				}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t</div>\r\n");

            
            #line 65 "..\..\Views\IlaroAdmin\Create.cshtml"
		}
	}

	
            
            #line default
            #line hidden
            
            #line 68 "..\..\Views\IlaroAdmin\Create.cshtml"
Write(Html.Hidden("EntityName", Model.Entity.Name));

            
            #line default
            #line hidden
            
            #line 68 "..\..\Views\IlaroAdmin\Create.cshtml"
                                              


            
            #line default
            #line hidden
WriteLiteral("\t<div");

WriteLiteral(" class=\"form-action\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"col-md-offset-2\"");

WriteLiteral(">\r\n\t\t\t<button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">");

            
            #line 72 "..\..\Views\IlaroAdmin\Create.cshtml"
                                            Write(IlaroAdminResources.Save);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n\t\t\t<button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" name=\"ContinueEdit\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-edit\"");

WriteLiteral("></i> ");

            
            #line 73 "..\..\Views\IlaroAdmin\Create.cshtml"
                                                                                                         Write(IlaroAdminResources.SaveAndContinueEdit);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n\t\t\t<button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" name=\"AddNext\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-plus\"");

WriteLiteral("></i> ");

            
            #line 74 "..\..\Views\IlaroAdmin\Create.cshtml"
                                                                                                    Write(IlaroAdminResources.SaveAndAddNext);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n\t\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 2843), Tuple.Create("\"", 2909)
            
            #line 75 "..\..\Views\IlaroAdmin\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2850), Tuple.Create<System.Object, System.Int32>(Url.Action("List", new { entityName = Model.Entity.Name })
            
            #line default
            #line hidden
, 2850), false)
);

WriteLiteral(" class=\"btn btn-link\"");

WriteLiteral(">");

            
            #line 75 "..\..\Views\IlaroAdmin\Create.cshtml"
                                                                                         Write(IlaroAdminResources.Cancel);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n\t\t</div>\r\n\t</div>\r\n");

            
            #line 78 "..\..\Views\IlaroAdmin\Create.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"foreign-modal\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"Create foreign entity\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:90%\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n\t\t\t<div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n\t\t\t\t<button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</button>\r\n\t\t\t\t<h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" id=\"myModalLabel\"");

WriteLiteral(">Create foreign entity</h4>\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
