using System;
using System.CodeDom.Compiler;
using System.Linq;
using System.Web.Mvc;
using System.Web.Mvc.Html;
using System.Web.WebPages;
using Ilaro.Admin.Extensions;
using Ilaro.Admin.ViewModels;
using Resources;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilaro.Admin.Views.IlaroAdmin
{
    [GeneratedCode("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Views/IlaroAdmin/Delete.cshtml")]
    public partial class Delete : WebViewPage<DeleteViewModel>
    {

#line 57 "..\..\Views\IlaroAdmin\Delete.cshtml"
public HelperResult DisplayRecordHierarchy(RecordHierarchy record)
{
#line default
#line hidden
return new HelperResult(__razor_helper_writer => {

#line 58 "..\..\Views\IlaroAdmin\Delete.cshtml"
 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\t<li>\r\n");

WriteLiteralTo(__razor_helper_writer, "\t\t");


#line 60 "..\..\Views\IlaroAdmin\Delete.cshtml"
WriteTo(__razor_helper_writer, record.Entity.Name);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, ": ");


#line 60 "..\..\Views\IlaroAdmin\Delete.cshtml"
WriteTo(__razor_helper_writer, Html.ActionLink(record.DisplayName, "Edit", new { entityName = record.Entity.Name, key = record.KeyValue }));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 61 "..\..\Views\IlaroAdmin\Delete.cshtml"
		

#line default
#line hidden

#line 61 "..\..\Views\IlaroAdmin\Delete.cshtml"
   if (record.SubRecordsHierarchies.Any())
		{


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\t\t\t<ul>\r\n");


#line 64 "..\..\Views\IlaroAdmin\Delete.cshtml"
				

#line default
#line hidden

#line 64 "..\..\Views\IlaroAdmin\Delete.cshtml"
     foreach (var subRecord in record.SubRecordsHierarchies)
				{


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\t\t\t\t\t");


#line 66 "..\..\Views\IlaroAdmin\Delete.cshtml"
WriteTo(__razor_helper_writer, DisplayRecordHierarchy(subRecord));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 67 "..\..\Views\IlaroAdmin\Delete.cshtml"
				}


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\t\t\t</ul>\r\n");


#line 69 "..\..\Views\IlaroAdmin\Delete.cshtml"
		}


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\t</li>\r\n");


#line 71 "..\..\Views\IlaroAdmin\Delete.cshtml"


#line default
#line hidden
});

#line 71 "..\..\Views\IlaroAdmin\Delete.cshtml"
}
#line default
#line hidden

        public Delete()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\IlaroAdmin\Delete.cshtml"
  
	Layout = "~/Views/IlaroAdmin/_Layout.cshtml";
	ViewBag.Title = string.Format(IlaroAdminResources.Delete_Title, Model.Entity.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("Breadcrumb", () => {

WriteLiteral("\r\n\t<ul");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral(">\r\n\t\t<li>");

            
            #line 10 "..\..\Views\IlaroAdmin\Delete.cshtml"
 Write(Html.ActionLink(IlaroAdminResources.Index_Title, "Index"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n\t\t<li>");

            
            #line 11 "..\..\Views\IlaroAdmin\Delete.cshtml"
 Write(Html.ActionLink(Model.Entity.GroupName, "Group", new { groupName = Model.Entity.GroupName }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n\t\t<li>");

            
            #line 12 "..\..\Views\IlaroAdmin\Delete.cshtml"
 Write(Html.ActionLink(Model.Entity.Plural, "List", new { entityName = Model.Entity.Name }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n\t\t<li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">");

            
            #line 13 "..\..\Views\IlaroAdmin\Delete.cshtml"
                Write(string.Format(IlaroAdminResources.Delete_Title, Model.Entity.Name));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n\t</ul>\r\n");

});

WriteLiteral("\r\n<h2>");

            
            #line 17 "..\..\Views\IlaroAdmin\Delete.cshtml"
Write(Model.Entity.Singular);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n\r\n");

            
            #line 19 "..\..\Views\IlaroAdmin\Delete.cshtml"
 using (Html.BeginForm("Delete", "IlaroAdmin", FormMethod.Post, new { @class = "form-horizontal" }))
{
	
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\IlaroAdmin\Delete.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\IlaroAdmin\Delete.cshtml"
                         
	
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\IlaroAdmin\Delete.cshtml"
Write(Html.ValidationSummary());

            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\IlaroAdmin\Delete.cshtml"
                          
	
            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\IlaroAdmin\Delete.cshtml"
Write(Html.Hidden("EntityName", Model.Entity.Name));

            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\IlaroAdmin\Delete.cshtml"
                                              
	
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\IlaroAdmin\Delete.cshtml"
Write(Html.Hidden("Key", Model.Entity.Key.Value));

            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\IlaroAdmin\Delete.cshtml"
                                            


            
            #line default
            #line hidden
WriteLiteral("\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"controls col-md-3\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t");

            
            #line 28 "..\..\Views\IlaroAdmin\Delete.cshtml"
Write(IlaroAdminResources.DeleteText);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t</div>\r\n\t</div>\r\n");

            
            #line 31 "..\..\Views\IlaroAdmin\Delete.cshtml"

	for (int i = 0; i < Model.PropertiesDeleteOptions.Count; i++)
	{

            
            #line default
            #line hidden
WriteLiteral("\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n\t\t\t<label");

WriteAttribute("for", Tuple.Create(" for=\"", 1178), Tuple.Create("\"", 1247)
            
            #line 35 "..\..\Views\IlaroAdmin\Delete.cshtml"
, Tuple.Create(Tuple.Create("", 1184), Tuple.Create<Object, Int32>(Html.IdFor(m => Model.PropertiesDeleteOptions[i].DeleteOption)
            
            #line default
            #line hidden
, 1184), false)
);

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">");

            
            #line 35 "..\..\Views\IlaroAdmin\Delete.cshtml"
                                                                                                          Write(Model.PropertiesDeleteOptions[i].PropertyName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n\t\t\t<div");

WriteLiteral(" class=\"controls col-md-3\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 37 "..\..\Views\IlaroAdmin\Delete.cshtml"
Write(Html.HiddenFor(m => Model.PropertiesDeleteOptions[i].PropertyName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 38 "..\..\Views\IlaroAdmin\Delete.cshtml"
Write(Html.DropDownListFor(m => Model.PropertiesDeleteOptions[i].DeleteOption, Model.PropertiesDeleteOptions[i].DeleteOption.GetSelectList(), new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</div>\r\n\t\t</div>\r\n");

            
            #line 41 "..\..\Views\IlaroAdmin\Delete.cshtml"
	}
	

            
            #line default
            #line hidden
WriteLiteral("\t<h4>If all foreign entities are to be cascade delete, all of the following items" +
" will be deleted:</h4>\r\n");

WriteLiteral("\t<ul");

WriteLiteral(" class=\"list-delete\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t");

            
            #line 45 "..\..\Views\IlaroAdmin\Delete.cshtml"
Write(DisplayRecordHierarchy(Model.RecordHierarchy));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t</ul>\r\n");

            
            #line 47 "..\..\Views\IlaroAdmin\Delete.cshtml"


            
            #line default
            #line hidden
WriteLiteral("\t<div");

WriteLiteral(" class=\"form-action\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"col-md-offset-2\"");

WriteLiteral(">\r\n\t\t\t<button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">");

            
            #line 50 "..\..\Views\IlaroAdmin\Delete.cshtml"
                                            Write(IlaroAdminResources.Delete);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n\t\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 2003), Tuple.Create("\"", 2029)
            
            #line 51 "..\..\Views\IlaroAdmin\Delete.cshtml"
, Tuple.Create(Tuple.Create("", 2010), Tuple.Create<Object, Int32>(Url.Action("Edit")
            
            #line default
            #line hidden
, 2010), false)
);

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-edit\"");

WriteLiteral("></i> ");

            
            #line 51 "..\..\Views\IlaroAdmin\Delete.cshtml"
                                                                                             Write(IlaroAdminResources.Edit);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n\t\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 2142), Tuple.Create("\"", 2168)
            
            #line 52 "..\..\Views\IlaroAdmin\Delete.cshtml"
, Tuple.Create(Tuple.Create("", 2149), Tuple.Create<Object, Int32>(Url.Action("List")
            
            #line default
            #line hidden
, 2149), false)
);

WriteLiteral(" class=\"btn btn-link\"");

WriteLiteral(">");

            
            #line 52 "..\..\Views\IlaroAdmin\Delete.cshtml"
                                                 Write(IlaroAdminResources.Cancel);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n\t\t</div>\r\n\t</div>\r\n");

            
            #line 55 "..\..\Views\IlaroAdmin\Delete.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
