#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilaro.Admin.Views.IlaroAdmin
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Ilaro.Admin.Commons.Paging;
    using Ilaro.Admin.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/IlaroAdmin/Details.cshtml")]
    public partial class Details : System.Web.Mvc.WebViewPage<Ilaro.Admin.ViewModels.DetailsViewModel>
    {
        public Details()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\IlaroAdmin\Details.cshtml"
  
    Layout = "~/Views/IlaroAdmin/_Layout.cshtml";
    ViewBag.Title = Model.Entity.Plural;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("Breadcrumb", () => {

WriteLiteral("\r\n    <ul");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral(">\r\n        <li>");

            
            #line 11 "..\..\Views\IlaroAdmin\Details.cshtml"
       Write(Html.ActionLink(Resources.IlaroAdminResources.Index_Title, "Index"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n        <li>");

            
            #line 12 "..\..\Views\IlaroAdmin\Details.cshtml"
       Write(Html.ActionLink(Model.Entity.GroupName, "Group", new { groupName = Model.Entity.GroupName }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n        <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">");

            
            #line 13 "..\..\Views\IlaroAdmin\Details.cshtml"
                      Write(Model.Entity.Plural);

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n    </ul>\r\n");

});

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n    <h2");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">");

            
            #line 18 "..\..\Views\IlaroAdmin\Details.cshtml"
                     Write(Model.Entity.Plural);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n");

            
            #line 19 "..\..\Views\IlaroAdmin\Details.cshtml"
    
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\IlaroAdmin\Details.cshtml"
     if (Model.IsSearchActive)
    {
        using (Html.BeginForm("Details", "IlaroAdmin", new { page = Model.PagerInfo.Current }, FormMethod.Get, new { @class = "pull-left col-md-3" }))
        {
            foreach (var filter in Model.ActiveFilters)
            {
                
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\IlaroAdmin\Details.cshtml"
           Write(Html.Hidden(filter.Property.Name, filter.Value));

            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\IlaroAdmin\Details.cshtml"
                                                                
            }
            
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\IlaroAdmin\Details.cshtml"
       Write(Html.Hidden("entityName", Model.Entity.Name));

            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\IlaroAdmin\Details.cshtml"
                                                         
            
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\IlaroAdmin\Details.cshtml"
       Write(Html.Hidden("pp", Model.PerPage));

            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\IlaroAdmin\Details.cshtml"
                                             
            
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\IlaroAdmin\Details.cshtml"
       Write(Html.Hidden("o", Model.Order));

            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\IlaroAdmin\Details.cshtml"
                                          
            
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\IlaroAdmin\Details.cshtml"
       Write(Html.Hidden("od", Model.OrderDirection));

            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\IlaroAdmin\Details.cshtml"
                                                    

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 32 "..\..\Views\IlaroAdmin\Details.cshtml"
           Write(Html.TextBox("sq", Model.SearchQuery, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(">");

            
            #line 34 "..\..\Views\IlaroAdmin\Details.cshtml"
                                                             Write(Resources.IlaroAdminResources.Search);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                </span>\r\n            </div>\r\n");

            
            #line 37 "..\..\Views\IlaroAdmin\Details.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 39 "..\..\Views\IlaroAdmin\Details.cshtml"
Write(Html.ActionLink(Resources.IlaroAdminResources.Changes, "Changes", new { entityName = Model.Entity.Name }, new { @class = "btn btn-link pull-left" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 41 "..\..\Views\IlaroAdmin\Details.cshtml"
    
            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\IlaroAdmin\Details.cshtml"
     if (Model.Entity.CanAdd)
    {

            
            #line default
            #line hidden
WriteLiteral("        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1668), Tuple.Create("\"", 1736)
            
            #line 43 "..\..\Views\IlaroAdmin\Details.cshtml"
, Tuple.Create(Tuple.Create("", 1675), Tuple.Create<System.Object, System.Int32>(Url.Action("Create", new { entityName = Model.Entity.Name })
            
            #line default
            #line hidden
, 1675), false)
);

WriteLiteral(" class=\"btn btn-primary pull-right\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphglyphicon glyphicon-plus\"");

WriteLiteral("></span> ");

            
            #line 43 "..\..\Views\IlaroAdmin\Details.cshtml"
                                                                                                                                                                            Write(Resources.IlaroAdminResources.Add);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 44 "..\..\Views\IlaroAdmin\Details.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n<table");

WriteLiteral(" id=\"entity-table\"");

WriteLiteral(" class=\"table table-striped table-bordered table-hover\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n            ");

WriteLiteral("\r\n");

            
            #line 51 "..\..\Views\IlaroAdmin\Details.cshtml"
            
            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\IlaroAdmin\Details.cshtml"
             foreach (var column in Model.Columns)
            {

            
            #line default
            #line hidden
WriteLiteral("                <th>\r\n                    <span ");

            
            #line 54 "..\..\Views\IlaroAdmin\Details.cshtml"
                     Write(Html.Condition(!string.IsNullOrEmpty(column.Description), () => "title=\"" + column.Description + "\""));

            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 55 "..\..\Views\IlaroAdmin\Details.cshtml"
                   Write(Html.SortColumnLink(Model.Entity, column, Model.Filters, Model.SearchQuery, Model.PerPage));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <i");

WriteAttribute("class", Tuple.Create(" class=\"", 2451), Tuple.Create("\"", 2508)
, Tuple.Create(Tuple.Create("", 2459), Tuple.Create("glyphicon", 2459), true)
, Tuple.Create(Tuple.Create(" ", 2468), Tuple.Create("glyphicon-chevron-", 2469), true)
            
            #line 56 "..\..\Views\IlaroAdmin\Details.cshtml"
, Tuple.Create(Tuple.Create("", 2487), Tuple.Create<System.Object, System.Int32>(column.SortDirection
            
            #line default
            #line hidden
, 2487), false)
);

WriteLiteral("></i>\r\n                    </span>\r\n                </th>\r\n");

            
            #line 59 "..\..\Views\IlaroAdmin\Details.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 60 "..\..\Views\IlaroAdmin\Details.cshtml"
             if (Model.Entity.LinksCount > 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteAttribute("colspan", Tuple.Create(" colspan=\"", 2664), Tuple.Create("\"", 2698)
            
            #line 62 "..\..\Views\IlaroAdmin\Details.cshtml"
, Tuple.Create(Tuple.Create("", 2674), Tuple.Create<System.Object, System.Int32>(Model.Entity.LinksCount
            
            #line default
            #line hidden
, 2674), false)
);

WriteLiteral("></th>\r\n");

            
            #line 63 "..\..\Views\IlaroAdmin\Details.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 67 "..\..\Views\IlaroAdmin\Details.cshtml"
        
            
            #line default
            #line hidden
            
            #line 67 "..\..\Views\IlaroAdmin\Details.cshtml"
         foreach (var row in Model.Data)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                ");

WriteLiteral("\r\n");

            
            #line 71 "..\..\Views\IlaroAdmin\Details.cshtml"
                
            
            #line default
            #line hidden
            
            #line 71 "..\..\Views\IlaroAdmin\Details.cshtml"
                 foreach (var item in row.Values)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td>");

            
            #line 73 "..\..\Views\IlaroAdmin\Details.cshtml"
                   Write(Html.DisplayFor(m => item, item.Property.DisplayTemplateName));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 74 "..\..\Views\IlaroAdmin\Details.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 75 "..\..\Views\IlaroAdmin\Details.cshtml"
                 if (!Model.Entity.DisplayLink.IsNullOrEmpty())
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"min-width\"");

WriteLiteral(">\r\n                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3248), Tuple.Create("\"", 3313)
            
            #line 78 "..\..\Views\IlaroAdmin\Details.cshtml"
, Tuple.Create(Tuple.Create("", 3255), Tuple.Create<System.Object, System.Int32>(string.Format(Model.Entity.DisplayLink, row.LinkKeyValue)
            
            #line default
            #line hidden
, 3255), false)
);

WriteLiteral(" class=\"btn btn-xs btn-link\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphglyphicon glyphicon-eye-open\"");

WriteLiteral("></span> ");

            
            #line 78 "..\..\Views\IlaroAdmin\Details.cshtml"
                                                                                                                                                                                      Write(Resources.IlaroAdminResources.View);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                    </td>\r\n");

            
            #line 80 "..\..\Views\IlaroAdmin\Details.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 81 "..\..\Views\IlaroAdmin\Details.cshtml"
                 if (Model.Entity.HasEditLink)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"min-width\"");

WriteLiteral(">\r\n");

            
            #line 84 "..\..\Views\IlaroAdmin\Details.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 84 "..\..\Views\IlaroAdmin\Details.cshtml"
                         if (!Model.Entity.EditLink.IsNullOrEmpty())
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3734), Tuple.Create("\"", 3796)
            
            #line 86 "..\..\Views\IlaroAdmin\Details.cshtml"
, Tuple.Create(Tuple.Create("", 3741), Tuple.Create<System.Object, System.Int32>(string.Format(Model.Entity.EditLink, row.LinkKeyValue)
            
            #line default
            #line hidden
, 3741), false)
);

WriteLiteral(" class=\"btn btn-xs btn-link\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphglyphicon glyphicon-edit\"");

WriteLiteral("></span> ");

            
            #line 86 "..\..\Views\IlaroAdmin\Details.cshtml"
                                                                                                                                                                                   Write(Resources.IlaroAdminResources.Edit);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 87 "..\..\Views\IlaroAdmin\Details.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4043), Tuple.Create("\"", 4129)
            
            #line 90 "..\..\Views\IlaroAdmin\Details.cshtml"
, Tuple.Create(Tuple.Create("", 4050), Tuple.Create<System.Object, System.Int32>(Url.Action("Edit", new { entityName = Model.Entity.Name, key = row.KeyValue })
            
            #line default
            #line hidden
, 4050), false)
);

WriteLiteral(" class=\"btn btn-xs btn-link\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphglyphicon glyphicon-edit\"");

WriteLiteral("></span> ");

            
            #line 90 "..\..\Views\IlaroAdmin\Details.cshtml"
                                                                                                                                                                                                           Write(Resources.IlaroAdminResources.Edit);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 91 "..\..\Views\IlaroAdmin\Details.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </td>\r\n");

            
            #line 93 "..\..\Views\IlaroAdmin\Details.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 94 "..\..\Views\IlaroAdmin\Details.cshtml"
                 if (Model.Entity.HasDeleteLink)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"min-width\"");

WriteLiteral(">\r\n");

            
            #line 97 "..\..\Views\IlaroAdmin\Details.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 97 "..\..\Views\IlaroAdmin\Details.cshtml"
                         if (!Model.Entity.DeleteLink.IsNullOrEmpty())
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4577), Tuple.Create("\"", 4641)
            
            #line 99 "..\..\Views\IlaroAdmin\Details.cshtml"
, Tuple.Create(Tuple.Create("", 4584), Tuple.Create<System.Object, System.Int32>(string.Format(Model.Entity.DeleteLink, row.LinkKeyValue)
            
            #line default
            #line hidden
, 4584), false)
);

WriteLiteral(" class=\"btn btn-xs btn-link text-danger\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphglyphicon glyphicon-remove\"");

WriteLiteral("></span> ");

            
            #line 99 "..\..\Views\IlaroAdmin\Details.cshtml"
                                                                                                                                                                                                   Write(Resources.IlaroAdminResources.Delete);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 100 "..\..\Views\IlaroAdmin\Details.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4904), Tuple.Create("\"", 4992)
            
            #line 103 "..\..\Views\IlaroAdmin\Details.cshtml"
, Tuple.Create(Tuple.Create("", 4911), Tuple.Create<System.Object, System.Int32>(Url.Action("Delete", new { entityName = Model.Entity.Name, key = row.KeyValue })
            
            #line default
            #line hidden
, 4911), false)
);

WriteLiteral(" class=\"btn btn-xs btn-link text-danger\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphglyphicon glyphicon-remove\"");

WriteLiteral("></span> ");

            
            #line 103 "..\..\Views\IlaroAdmin\Details.cshtml"
                                                                                                                                                                                                                           Write(Resources.IlaroAdminResources.Delete);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 104 "..\..\Views\IlaroAdmin\Details.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </td>\r\n");

            
            #line 106 "..\..\Views\IlaroAdmin\Details.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n");

            
            #line 108 "..\..\Views\IlaroAdmin\Details.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>\r\n\r\n<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(" style=\"margin-right:10px\"");

WriteLiteral(">\r\n");

            
            #line 114 "..\..\Views\IlaroAdmin\Details.cshtml"
        
            
            #line default
            #line hidden
            
            #line 114 "..\..\Views\IlaroAdmin\Details.cshtml"
         using (Html.BeginForm("Details", "IlaroAdmin", new { page = Model.PagerInfo.Current }, FormMethod.Get, new { @class = "form-inline" }))
        {
            foreach (var filter in Model.ActiveFilters)
            {
                
            
            #line default
            #line hidden
            
            #line 118 "..\..\Views\IlaroAdmin\Details.cshtml"
           Write(Html.Hidden(filter.Property.Name, filter.Value));

            
            #line default
            #line hidden
            
            #line 118 "..\..\Views\IlaroAdmin\Details.cshtml"
                                                                
            }
            
            
            #line default
            #line hidden
            
            #line 120 "..\..\Views\IlaroAdmin\Details.cshtml"
       Write(Html.Hidden("entityName", Model.Entity.Name));

            
            #line default
            #line hidden
            
            #line 120 "..\..\Views\IlaroAdmin\Details.cshtml"
                                                         
            
            
            #line default
            #line hidden
            
            #line 121 "..\..\Views\IlaroAdmin\Details.cshtml"
       Write(Html.Hidden("sq", Model.SearchQuery));

            
            #line default
            #line hidden
            
            #line 121 "..\..\Views\IlaroAdmin\Details.cshtml"
                                                 
            
            
            #line default
            #line hidden
            
            #line 122 "..\..\Views\IlaroAdmin\Details.cshtml"
       Write(Html.Hidden("o", Model.Order));

            
            #line default
            #line hidden
            
            #line 122 "..\..\Views\IlaroAdmin\Details.cshtml"
                                          
            
            
            #line default
            #line hidden
            
            #line 123 "..\..\Views\IlaroAdmin\Details.cshtml"
       Write(Html.Hidden("od", Model.OrderDirection));

            
            #line default
            #line hidden
            
            #line 123 "..\..\Views\IlaroAdmin\Details.cshtml"
                                                    

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"pp\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">");

            
            #line 125 "..\..\Views\IlaroAdmin\Details.cshtml"
                                                 Write(Resources.IlaroAdminResources.OnPage);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n");

WriteLiteral("                ");

            
            #line 126 "..\..\Views\IlaroAdmin\Details.cshtml"
           Write(Html.DropDownList("pp", 
                 new SelectList(new Dictionary<int, int> { { 5, 5 }, { 10, 10 }, { 15, 15 }, { 20, 20 }, { 25, 25 }, { 50, 50 }, { 100, 100 } }, "Key", "Value", 10),
                 new Dictionary<string, object>{ { "class", "autoPostBack select-sm"}, { "data-width", "70px" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

            
            #line 130 "..\..\Views\IlaroAdmin\Details.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(" style=\"margin-right:10px\"");

WriteLiteral(">\r\n");

            
            #line 134 "..\..\Views\IlaroAdmin\Details.cshtml"
        
            
            #line default
            #line hidden
            
            #line 134 "..\..\Views\IlaroAdmin\Details.cshtml"
          Html.RenderPartial("_Paging", Model.PagerInfo);
            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(" style=\"line-height:29px\"");

WriteLiteral(">");

            
            #line 137 "..\..\Views\IlaroAdmin\Details.cshtml"
                                               Write(Resources.IlaroAdminResources.Founded);

            
            #line default
            #line hidden
WriteLiteral(" <strong>");

            
            #line 137 "..\..\Views\IlaroAdmin\Details.cshtml"
                                                                                              Write(Model.PagerInfo.TotalItems);

            
            #line default
            #line hidden
WriteLiteral("</strong></div>\r\n</div>\r\n\r\n");

DefineSection("Sidebar", () => {

WriteLiteral("\r\n");

            
            #line 142 "..\..\Views\IlaroAdmin\Details.cshtml"
    
            
            #line default
            #line hidden
            
            #line 142 "..\..\Views\IlaroAdmin\Details.cshtml"
     if (Model.Filters.Count > 0)
    {

            
            #line default
            #line hidden
WriteLiteral("        <h2>");

            
            #line 144 "..\..\Views\IlaroAdmin\Details.cshtml"
       Write(Resources.IlaroAdminResources.Filters);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n");

WriteLiteral("        <ul");

WriteLiteral(" class=\"nav nav-list\"");

WriteLiteral(">\r\n            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6832), Tuple.Create("\"", 6933)
            
            #line 146 "..\..\Views\IlaroAdmin\Details.cshtml"
, Tuple.Create(Tuple.Create("", 6839), Tuple.Create<System.Object, System.Int32>(Url.Action("Details", new { entityName = Model.Entity.Name, page = Model.PagerInfo.Current })
            
            #line default
            #line hidden
, 6839), false)
);

WriteLiteral(">");

            
            #line 146 "..\..\Views\IlaroAdmin\Details.cshtml"
                                                                                                                    Write(Resources.IlaroAdminResources.RemoveFilters);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 147 "..\..\Views\IlaroAdmin\Details.cshtml"
            
            
            #line default
            #line hidden
            
            #line 147 "..\..\Views\IlaroAdmin\Details.cshtml"
             foreach (var filter in Model.Filters)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li");

WriteLiteral(" class=\"nav-header\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 151 "..\..\Views\IlaroAdmin\Details.cshtml"
               Write(filter.Property.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n");

            
            #line 153 "..\..\Views\IlaroAdmin\Details.cshtml"
                foreach (var option in filter.Options)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li ");

            
            #line 155 "..\..\Views\IlaroAdmin\Details.cshtml"
                   Write(Html.Condition(option.Selected, () => "class=\"active\""));

            
            #line default
            #line hidden
WriteLiteral(">");

            
            #line 155 "..\..\Views\IlaroAdmin\Details.cshtml"
                                                                              Write(Html.FilterOptionLink(Model.Entity, filter, option, Model.Filters, Model.SearchQuery, Model.Order, Model.OrderDirection, Model.PerPage));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

            
            #line 156 "..\..\Views\IlaroAdmin\Details.cshtml"
                }
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n");

            
            #line 159 "..\..\Views\IlaroAdmin\Details.cshtml"
    }

            
            #line default
            #line hidden
});

WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        $().ready(function () {
            $('table th #check-all').click(function () {
                var $this = $(this);
                var isChecked = $this.prop('checked');
                $this.parents('table').find('.row-checkbox').prop('checked', isChecked);
            });
            $('table tr').click(function () {
                var $this = $(this);
                var $checkbox = $this.find('.row-checkbox');
                //$checkbox.prop('checked', !$checkbox.prop('checked'));
            });
        });
    </script>
");

});

        }
    }
}
#pragma warning restore 1591
