#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilaro.Admin.Views.IlaroAdmin
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Ilaro.Admin.Commons.Paging;
    using Ilaro.Admin.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/IlaroAdmin/Details.cshtml")]
    public partial class Details : System.Web.Mvc.WebViewPage<Ilaro.Admin.ViewModels.DetailsViewModel>
    {
        public Details()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\IlaroAdmin\Details.cshtml"
  
    Layout = "~/Views/IlaroAdmin/_Layout.cshtml";
    ViewBag.Title = Model.Entity.Plural;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("Breadcrumb", () => {

WriteLiteral("\r\n<ul");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral(">\r\n    <li>");

            
            #line 11 "..\..\Views\IlaroAdmin\Details.cshtml"
   Write(Html.ActionLink("Admin", "Index"));

            
            #line default
            #line hidden
WriteLiteral(" <span");

WriteLiteral(" class=\"divider\"");

WriteLiteral(">/</span></li>\r\n    <li>");

            
            #line 12 "..\..\Views\IlaroAdmin\Details.cshtml"
   Write(Html.ActionLink(Model.Entity.GroupName, "Group", new { groupName = Model.Entity.GroupName }));

            
            #line default
            #line hidden
WriteLiteral(" <span");

WriteLiteral(" class=\"divider\"");

WriteLiteral(">/</span></li>\r\n    <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">");

            
            #line 13 "..\..\Views\IlaroAdmin\Details.cshtml"
                  Write(Model.Entity.Plural);

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n</ul>\r\n");

});

WriteLiteral("\r\n<h2>");

            
            #line 17 "..\..\Views\IlaroAdmin\Details.cshtml"
Write(Model.Entity.Plural);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n\r\n<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 545), Tuple.Create("\"", 613)
            
            #line 20 "..\..\Views\IlaroAdmin\Details.cshtml"
, Tuple.Create(Tuple.Create("", 552), Tuple.Create<System.Object, System.Int32>(Url.Action("Create", new { entityName = Model.Entity.Name })
            
            #line default
            #line hidden
, 552), false)
);

WriteLiteral(" class=\"btn btn-primary pull-right space-bottom\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-plus\"");

WriteLiteral("></i> Add</a>\r\n\r\n");

            
            #line 22 "..\..\Views\IlaroAdmin\Details.cshtml"
    
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\IlaroAdmin\Details.cshtml"
     if (Model.IsSearchActive)
    {
        using (Html.BeginForm("Details", "IlaroAdmin", new { page = Model.PagerInfo.Current }, FormMethod.Get))
        {
            foreach (var filter in Model.ActiveFilters)
            {
                
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\IlaroAdmin\Details.cshtml"
           Write(Html.Hidden(filter.Property.Name, filter.Value));

            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\IlaroAdmin\Details.cshtml"
                                                                
            }
            
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\IlaroAdmin\Details.cshtml"
       Write(Html.Hidden("entityName", Model.Entity.Name));

            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\IlaroAdmin\Details.cshtml"
                                                         
            
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\IlaroAdmin\Details.cshtml"
       Write(Html.Hidden("pp", Model.PerPage));

            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\IlaroAdmin\Details.cshtml"
                                             
            
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\IlaroAdmin\Details.cshtml"
       Write(Html.Hidden("o", Model.Order));

            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\IlaroAdmin\Details.cshtml"
                                          
            
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\IlaroAdmin\Details.cshtml"
       Write(Html.Hidden("od", Model.OrderDirection));

            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\IlaroAdmin\Details.cshtml"
                                                    

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"input-append\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 35 "..\..\Views\IlaroAdmin\Details.cshtml"
           Write(Html.TextBox("sq", Model.SearchQuery, new { @class = "span2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <button");

WriteLiteral(" class=\"btn\"");

WriteLiteral(">Search</button>\r\n            </div>\r\n");

            
            #line 38 "..\..\Views\IlaroAdmin\Details.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n<table");

WriteLiteral(" class=\"table table-striped table-bordered table-hover\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n            <th");

WriteLiteral(" class=\"min-width\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"check-all\"");

WriteLiteral(" /></th>\r\n");

            
            #line 46 "..\..\Views\IlaroAdmin\Details.cshtml"
            
            
            #line default
            #line hidden
            
            #line 46 "..\..\Views\IlaroAdmin\Details.cshtml"
             foreach (var column in Model.Columns)
            { 

            
            #line default
            #line hidden
WriteLiteral("                <th>\r\n                    <span ");

            
            #line 49 "..\..\Views\IlaroAdmin\Details.cshtml"
                     Write(Html.Condition(!string.IsNullOrEmpty(column.Description), () => "title=\"" + column.Description + "\""));

            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 50 "..\..\Views\IlaroAdmin\Details.cshtml"
                   Write(Html.SortColumnLink(Model.Entity, column, Model.Filters, Model.SearchQuery, Model.PerPage));

            
            #line default
            #line hidden
WriteLiteral(" \r\n                        <i");

WriteAttribute("class", Tuple.Create(" class=\"", 1982), Tuple.Create("\"", 2024)
, Tuple.Create(Tuple.Create("", 1990), Tuple.Create("icon-chevron-", 1990), true)
            
            #line 51 "..\..\Views\IlaroAdmin\Details.cshtml"
, Tuple.Create(Tuple.Create("", 2003), Tuple.Create<System.Object, System.Int32>(column.SortDirection
            
            #line default
            #line hidden
, 2003), false)
);

WriteLiteral("></i>\r\n                    </span>\r\n                </th>\r\n");

            
            #line 54 "..\..\Views\IlaroAdmin\Details.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 55 "..\..\Views\IlaroAdmin\Details.cshtml"
             if (Model.Entity.LinksCount > 0)
            { 

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteAttribute("colspan", Tuple.Create(" colspan=\"", 2181), Tuple.Create("\"", 2215)
            
            #line 57 "..\..\Views\IlaroAdmin\Details.cshtml"
, Tuple.Create(Tuple.Create("", 2191), Tuple.Create<System.Object, System.Int32>(Model.Entity.LinksCount
            
            #line default
            #line hidden
, 2191), false)
);

WriteLiteral("></th>\r\n");

            
            #line 58 "..\..\Views\IlaroAdmin\Details.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 62 "..\..\Views\IlaroAdmin\Details.cshtml"
    
            
            #line default
            #line hidden
            
            #line 62 "..\..\Views\IlaroAdmin\Details.cshtml"
     foreach (var row in Model.Data)
    {

            
            #line default
            #line hidden
WriteLiteral("        <tr>\r\n            <td><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" class=\"row-checkbox\"");

WriteLiteral(" /></td>\r\n");

            
            #line 66 "..\..\Views\IlaroAdmin\Details.cshtml"
            
            
            #line default
            #line hidden
            
            #line 66 "..\..\Views\IlaroAdmin\Details.cshtml"
             foreach (var item in row.Values)
            {

            
            #line default
            #line hidden
WriteLiteral("                <td>");

            
            #line 68 "..\..\Views\IlaroAdmin\Details.cshtml"
               Write(Html.DisplayFor(m => item, item.Property.DisplayTemplateName));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 69 "..\..\Views\IlaroAdmin\Details.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 70 "..\..\Views\IlaroAdmin\Details.cshtml"
             if (!Model.Entity.DisplayLink.IsNullOrEmpty())
            { 

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" class=\"min-width\"");

WriteLiteral(">\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2714), Tuple.Create("\"", 2779)
            
            #line 73 "..\..\Views\IlaroAdmin\Details.cshtml"
, Tuple.Create(Tuple.Create("", 2721), Tuple.Create<System.Object, System.Int32>(string.Format(Model.Entity.DisplayLink, row.LinkKeyValue)
            
            #line default
            #line hidden
, 2721), false)
);

WriteLiteral(" class=\"btn btn-mini btn-link\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-eye-open\"");

WriteLiteral("></i> View</a>\r\n                </td>\r\n");

            
            #line 75 "..\..\Views\IlaroAdmin\Details.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 76 "..\..\Views\IlaroAdmin\Details.cshtml"
             if (Model.Entity.HasEditLink)
            { 

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" class=\"min-width\"");

WriteLiteral(">\r\n");

            
            #line 79 "..\..\Views\IlaroAdmin\Details.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 79 "..\..\Views\IlaroAdmin\Details.cshtml"
                     if (!Model.Entity.EditLink.IsNullOrEmpty())
                    { 

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3105), Tuple.Create("\"", 3167)
            
            #line 81 "..\..\Views\IlaroAdmin\Details.cshtml"
, Tuple.Create(Tuple.Create("", 3112), Tuple.Create<System.Object, System.Int32>(string.Format(Model.Entity.EditLink, row.LinkKeyValue)
            
            #line default
            #line hidden
, 3112), false)
);

WriteLiteral(" class=\"btn btn-mini btn-link\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-edit\"");

WriteLiteral("></i> Edit</a>\r\n");

            
            #line 82 "..\..\Views\IlaroAdmin\Details.cshtml"
                    }
                    else
                    { 

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3334), Tuple.Create("\"", 3420)
            
            #line 85 "..\..\Views\IlaroAdmin\Details.cshtml"
, Tuple.Create(Tuple.Create("", 3341), Tuple.Create<System.Object, System.Int32>(Url.Action("Edit", new { entityName = Model.Entity.Name, key = row.KeyValue })
            
            #line default
            #line hidden
, 3341), false)
);

WriteLiteral(" class=\"btn btn-mini btn-link\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-edit\"");

WriteLiteral("></i> Edit</a>\r\n");

            
            #line 86 "..\..\Views\IlaroAdmin\Details.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n");

            
            #line 88 "..\..\Views\IlaroAdmin\Details.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 89 "..\..\Views\IlaroAdmin\Details.cshtml"
             if (Model.Entity.HasDeleteLink)
            { 

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" class=\"min-width\"");

WriteLiteral(">\r\n");

            
            #line 92 "..\..\Views\IlaroAdmin\Details.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 92 "..\..\Views\IlaroAdmin\Details.cshtml"
                     if (!Model.Entity.DeleteLink.IsNullOrEmpty())
                    { 

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3769), Tuple.Create("\"", 3833)
            
            #line 94 "..\..\Views\IlaroAdmin\Details.cshtml"
, Tuple.Create(Tuple.Create("", 3776), Tuple.Create<System.Object, System.Int32>(string.Format(Model.Entity.DeleteLink, row.LinkKeyValue)
            
            #line default
            #line hidden
, 3776), false)
);

WriteLiteral(" class=\"btn btn-mini btn-link text-error\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-remove\"");

WriteLiteral("></i> Delete</a>\r\n");

            
            #line 95 "..\..\Views\IlaroAdmin\Details.cshtml"
                    }
                    else
                    { 

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4015), Tuple.Create("\"", 4101)
            
            #line 98 "..\..\Views\IlaroAdmin\Details.cshtml"
, Tuple.Create(Tuple.Create("", 4022), Tuple.Create<System.Object, System.Int32>(Url.Action("Edit", new { entityName = Model.Entity.Name, key = row.KeyValue })
            
            #line default
            #line hidden
, 4022), false)
);

WriteLiteral(" class=\"btn btn-mini btn-link text-error\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-remove\"");

WriteLiteral("></i> Delete</a>\r\n");

            
            #line 99 "..\..\Views\IlaroAdmin\Details.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n");

            
            #line 101 "..\..\Views\IlaroAdmin\Details.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n");

            
            #line 103 "..\..\Views\IlaroAdmin\Details.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>\r\n\r\n<p");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">Founded: <strong>");

            
            #line 107 "..\..\Views\IlaroAdmin\Details.cshtml"
                                  Write(Model.PagerInfo.TotalItems);

            
            #line default
            #line hidden
WriteLiteral("</strong></p>\r\n\r\n<div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(" style=\"margin-top:1px;\"");

WriteLiteral(">\r\n");

            
            #line 110 "..\..\Views\IlaroAdmin\Details.cshtml"
    
            
            #line default
            #line hidden
            
            #line 110 "..\..\Views\IlaroAdmin\Details.cshtml"
     using (Html.BeginForm("Details", "IlaroAdmin", new { page = Model.PagerInfo.Current }, FormMethod.Get, new { @class = "form-inline" }))
    {
        foreach (var filter in Model.ActiveFilters)
        {
            
            
            #line default
            #line hidden
            
            #line 114 "..\..\Views\IlaroAdmin\Details.cshtml"
       Write(Html.Hidden(filter.Property.Name, filter.Value));

            
            #line default
            #line hidden
            
            #line 114 "..\..\Views\IlaroAdmin\Details.cshtml"
                                                            
        }
        
            
            #line default
            #line hidden
            
            #line 116 "..\..\Views\IlaroAdmin\Details.cshtml"
   Write(Html.Hidden("entityName", Model.Entity.Name));

            
            #line default
            #line hidden
            
            #line 116 "..\..\Views\IlaroAdmin\Details.cshtml"
                                                     
        
            
            #line default
            #line hidden
            
            #line 117 "..\..\Views\IlaroAdmin\Details.cshtml"
   Write(Html.Hidden("sq", Model.SearchQuery));

            
            #line default
            #line hidden
            
            #line 117 "..\..\Views\IlaroAdmin\Details.cshtml"
                                             
        
            
            #line default
            #line hidden
            
            #line 118 "..\..\Views\IlaroAdmin\Details.cshtml"
   Write(Html.Hidden("o", Model.Order));

            
            #line default
            #line hidden
            
            #line 118 "..\..\Views\IlaroAdmin\Details.cshtml"
                                      
        
            
            #line default
            #line hidden
            
            #line 119 "..\..\Views\IlaroAdmin\Details.cshtml"
   Write(Html.Hidden("od", Model.OrderDirection));

            
            #line default
            #line hidden
            
            #line 119 "..\..\Views\IlaroAdmin\Details.cshtml"
                                                

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"control-group\"");

WriteLiteral(">\r\n            <label");

WriteLiteral(" for=\"pp\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">On Page:</label>\r\n");

WriteLiteral("            ");

            
            #line 122 "..\..\Views\IlaroAdmin\Details.cshtml"
       Write(Html.DropDownList("pp", new SelectList(new Dictionary<int, int> { { 5, 5 }, { 10, 10 }, { 15, 15 }, { 20, 20 }, { 25, 25 }, { 50, 50 }, { 100, 100 } }, "Key", "Value", 10), new { @class = "autoPostBack" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n");

            
            #line 124 "..\..\Views\IlaroAdmin\Details.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n<div");

WriteLiteral(" class=\"offset1\"");

WriteLiteral(">\r\n");

            
            #line 128 "..\..\Views\IlaroAdmin\Details.cshtml"
    
            
            #line default
            #line hidden
            
            #line 128 "..\..\Views\IlaroAdmin\Details.cshtml"
      Html.RenderPartial("_Paging", Model.PagerInfo);
            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n\r\n");

DefineSection("Sidebar", () => {

WriteLiteral("\r\n");

            
            #line 134 "..\..\Views\IlaroAdmin\Details.cshtml"
 if (Model.Filters.Count > 0)
{ 

            
            #line default
            #line hidden
WriteLiteral("<h2>Filters</h2>\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"sidebar-nav well\"");

WriteLiteral(">\r\n    <ul");

WriteLiteral(" class=\"nav nav-list\"");

WriteLiteral(">\r\n        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5503), Tuple.Create("\"", 5604)
            
            #line 139 "..\..\Views\IlaroAdmin\Details.cshtml"
, Tuple.Create(Tuple.Create("", 5510), Tuple.Create<System.Object, System.Int32>(Url.Action("Details", new { entityName = Model.Entity.Name, page = Model.PagerInfo.Current })
            
            #line default
            #line hidden
, 5510), false)
);

WriteLiteral(">Wyczyść filtry</a></li>\r\n");

            
            #line 140 "..\..\Views\IlaroAdmin\Details.cshtml"
        
            
            #line default
            #line hidden
            
            #line 140 "..\..\Views\IlaroAdmin\Details.cshtml"
         foreach (var filter in Model.Filters)
        { 

            
            #line default
            #line hidden
WriteLiteral("            <li");

WriteLiteral(" class=\"nav-header\"");

WriteLiteral(">\r\n                ");

WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 144 "..\..\Views\IlaroAdmin\Details.cshtml"
           Write(filter.Property.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n");

            
            #line 146 "..\..\Views\IlaroAdmin\Details.cshtml"
            foreach (var option in filter.Options)
            {

            
            #line default
            #line hidden
WriteLiteral("                <li ");

            
            #line 148 "..\..\Views\IlaroAdmin\Details.cshtml"
               Write(Html.Condition(option.Selected, () => "class=\"active\""));

            
            #line default
            #line hidden
WriteLiteral(">");

            
            #line 148 "..\..\Views\IlaroAdmin\Details.cshtml"
                                                                          Write(Html.FilterOptionLink(Model.Entity, filter, option, Model.Filters, Model.SearchQuery, Model.Order, Model.OrderDirection, Model.PerPage));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

            
            #line 149 "..\..\Views\IlaroAdmin\Details.cshtml"
            }
        }

            
            #line default
            #line hidden
WriteLiteral("    </ul>\r\n</div>\r\n");

            
            #line 153 "..\..\Views\IlaroAdmin\Details.cshtml"
}

            
            #line default
            #line hidden
});

WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    $().ready(function () {
        $('table th #check-all').click(function () {
            var $this = $(this);
            var isChecked = $this.prop('checked');
            $this.parents('table').find('.row-checkbox').prop('checked', isChecked);
        });
        $('table tr').click(function () {
            var $this = $(this);
            var $checkbox = $this.find('.row-checkbox');
            //$checkbox.prop('checked', !$checkbox.prop('checked'));
        });
    });
</script>
");

});

        }
    }
}
#pragma warning restore 1591
