#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ilaro.Admin.Views.IlaroAdmin
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Ilaro.Admin.Commons.Paging;
    using Ilaro.Admin.Extensions;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/IlaroAdmin/Edit.cshtml")]
    public partial class Edit : System.Web.Mvc.WebViewPage<Ilaro.Admin.ViewModels.EditViewModel>
    {
        public Edit()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\IlaroAdmin\Edit.cshtml"
  
	Layout = "~/Views/IlaroAdmin/_Layout.cshtml";
	ViewBag.Title = string.Format(Resources.IlaroAdminResources.Edit_Title, Model.Entity.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("Breadcrumb", () => {

WriteLiteral("\r\n\t<ul");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral(">\r\n\t\t<li>");

            
            #line 11 "..\..\Views\IlaroAdmin\Edit.cshtml"
 Write(Html.ActionLink(Resources.IlaroAdminResources.Index_Title, "Index"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n\t\t<li>");

            
            #line 12 "..\..\Views\IlaroAdmin\Edit.cshtml"
 Write(Html.ActionLink(Model.Entity.GroupName, "Group", new { groupName = Model.Entity.GroupName }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n\t\t<li>");

            
            #line 13 "..\..\Views\IlaroAdmin\Edit.cshtml"
 Write(Html.ActionLink(Model.Entity.Plural, "List", new { entityName = Model.Entity.Name }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n\t\t<li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">");

            
            #line 14 "..\..\Views\IlaroAdmin\Edit.cshtml"
                Write(string.Format(Resources.IlaroAdminResources.Edit_Title, Model.Entity.Name));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n\t</ul>\r\n");

});

WriteLiteral("\r\n<h2>");

            
            #line 18 "..\..\Views\IlaroAdmin\Edit.cshtml"
Write(Model.Entity.Singular);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n\r\n");

            
            #line 20 "..\..\Views\IlaroAdmin\Edit.cshtml"
 using (Html.BeginForm("Edit", "IlaroAdmin", FormMethod.Post, new { @class = "form-horizontal" }))
{
	
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\IlaroAdmin\Edit.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\IlaroAdmin\Edit.cshtml"
                         
	
            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\IlaroAdmin\Edit.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\IlaroAdmin\Edit.cshtml"
                              

	if (Model.PropertiesGroups.Count > 1)
	{
		foreach (var group in Model.PropertiesGroups)
		{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<fieldset>\r\n\t\t\t\t<legend>");

            
            #line 30 "..\..\Views\IlaroAdmin\Edit.cshtml"
       Write(group.GroupName);

            
            #line default
            #line hidden
WriteLiteral(" <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn pull-right\"");

WriteLiteral("><i");

WriteAttribute("class", Tuple.Create(" class=\"", 1037), Tuple.Create("\"", 1148)
            
            #line 30 "..\..\Views\IlaroAdmin\Edit.cshtml"
    , Tuple.Create(Tuple.Create("", 1045), Tuple.Create<System.Object, System.Int32>(Html.Condition(group.IsCollapsed, () => "glyphicon glyphicon-plus", () => "glyphicon glyphicon-minus")
            
            #line default
            #line hidden
, 1045), false)
);

WriteLiteral("></i></button></legend>\r\n\t\t\t\t<div");

WriteAttribute("class", Tuple.Create(" class=\"", 1182), Tuple.Create("\"", 1245)
, Tuple.Create(Tuple.Create("", 1190), Tuple.Create("fields", 1190), true)
            
            #line 31 "..\..\Views\IlaroAdmin\Edit.cshtml"
, Tuple.Create(Tuple.Create(" ", 1196), Tuple.Create<System.Object, System.Int32>(Html.Condition(group.IsCollapsed, () => "hide")
            
            #line default
            #line hidden
, 1197), false)
);

WriteLiteral(">\r\n");

            
            #line 32 "..\..\Views\IlaroAdmin\Edit.cshtml"
					
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\IlaroAdmin\Edit.cshtml"
      foreach (var property in group.Properties)
					{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t\t");

            
            #line 35 "..\..\Views\IlaroAdmin\Edit.cshtml"
  Write(Html.EditorFor(m => property, property.EditorTemplateName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 36 "..\..\Views\IlaroAdmin\Edit.cshtml"
							
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\IlaroAdmin\Edit.cshtml"
        if (property.IsForeignKey)
							{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 1463), Tuple.Create("\"", 1541)
            
            #line 38 "..\..\Views\IlaroAdmin\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1470), Tuple.Create<System.Object, System.Int32>(Url.Action("Create", new { entityName = property.ForeignEntity.Name })
            
            #line default
            #line hidden
, 1470), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" class=\"btn btn-primary create-foreign\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-plus\"");

WriteLiteral("></span></a>\r\n");

            
            #line 39 "..\..\Views\IlaroAdmin\Edit.cshtml"
							}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t\t</div>\r\n");

            
            #line 41 "..\..\Views\IlaroAdmin\Edit.cshtml"
					}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t</div>\r\n\t\t\t</fieldset>\r\n");

            
            #line 44 "..\..\Views\IlaroAdmin\Edit.cshtml"
		}
	}
	else if (Model.PropertiesGroups.Count == 1)
	{
		foreach (var property in Model.PropertiesGroups[0].Properties)
		{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 51 "..\..\Views\IlaroAdmin\Edit.cshtml"
Write(Html.EditorFor(m => property, property.EditorTemplateName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 52 "..\..\Views\IlaroAdmin\Edit.cshtml"
				
            
            #line default
            #line hidden
            
            #line 52 "..\..\Views\IlaroAdmin\Edit.cshtml"
     if (property.IsForeignKey)
				{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 1981), Tuple.Create("\"", 2059)
            
            #line 54 "..\..\Views\IlaroAdmin\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1988), Tuple.Create<System.Object, System.Int32>(Url.Action("Create", new { entityName = property.ForeignEntity.Name })
            
            #line default
            #line hidden
, 1988), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" class=\"btn btn-primary create-foreign\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-plus\"");

WriteLiteral("></span></a>\r\n");

            
            #line 55 "..\..\Views\IlaroAdmin\Edit.cshtml"
				}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t</div>\r\n");

            
            #line 57 "..\..\Views\IlaroAdmin\Edit.cshtml"
		}
	}

	
            
            #line default
            #line hidden
            
            #line 60 "..\..\Views\IlaroAdmin\Edit.cshtml"
Write(Html.Hidden("EntityName", Model.Entity.Name));

            
            #line default
            #line hidden
            
            #line 60 "..\..\Views\IlaroAdmin\Edit.cshtml"
                                              


            
            #line default
            #line hidden
WriteLiteral("\t<div");

WriteLiteral(" class=\"form-action\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"col-md-offset-2\"");

WriteLiteral(">\r\n\t\t\t<button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">");

            
            #line 64 "..\..\Views\IlaroAdmin\Edit.cshtml"
                                            Write(Resources.IlaroAdminResources.Save);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n\t\t\t<button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" name=\"ContinueEdit\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-edit\"");

WriteLiteral("></i> ");

            
            #line 65 "..\..\Views\IlaroAdmin\Edit.cshtml"
                                                                                                         Write(Resources.IlaroAdminResources.SaveAndContinueEdit);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n\t\t\t<button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" name=\"AddNext\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-plus\"");

WriteLiteral("></i> ");

            
            #line 66 "..\..\Views\IlaroAdmin\Edit.cshtml"
                                                                                                    Write(Resources.IlaroAdminResources.SaveAndAddNext);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n\t\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 2740), Tuple.Create("\"", 2806)
            
            #line 67 "..\..\Views\IlaroAdmin\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2747), Tuple.Create<System.Object, System.Int32>(Url.Action("List", new { entityName = Model.Entity.Name })
            
            #line default
            #line hidden
, 2747), false)
);

WriteLiteral(" class=\"btn btn-link\"");

WriteLiteral(">");

            
            #line 67 "..\..\Views\IlaroAdmin\Edit.cshtml"
                                                                                         Write(Resources.IlaroAdminResources.Cancel);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n\t\t\t<a");

WriteAttribute("href", Tuple.Create(" href=\"", 2877), Tuple.Create("\"", 2975)
            
            #line 68 "..\..\Views\IlaroAdmin\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2884), Tuple.Create<System.Object, System.Int32>(Url.Action("Delete", new { entityName = Model.Entity.Name, key = Model.Entity.Key.Value })
            
            #line default
            #line hidden
, 2884), false)
);

WriteLiteral(" class=\"btn btn-danger pull-right\"");

WriteLiteral(">");

            
            #line 68 "..\..\Views\IlaroAdmin\Edit.cshtml"
                                                                                                                                      Write(Resources.IlaroAdminResources.Delete);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n\t\t</div>\r\n\t</div>\r\n");

            
            #line 71 "..\..\Views\IlaroAdmin\Edit.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"foreign-modal\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"Create foreign entity\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:90%\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n\t\t\t<div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n\t\t\t\t<button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</button>\r\n\t\t\t\t<h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" id=\"myModalLabel\"");

WriteLiteral(">Create foreign entity</h4>\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
