#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Ilaro.Admin;
    using Ilaro.Admin.Core;
    using Ilaro.Admin.Core.Extensions;
    using Ilaro.Admin.Extensions;
    using Ilaro.Admin.Models;
    using Ilaro.Admin.Models.Paging;
    using Resources;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/IlaroAdmin/Views/Group/Index.cshtml")]
    public partial class _Areas_IlaroAdmin_Views_Group_Index_cshtml : System.Web.Mvc.WebViewPage<GroupIndexModel>
    {
        public _Areas_IlaroAdmin_Views_Group_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\IlaroAdmin\Views\Group\Index.cshtml"
  
    Layout = "~/Areas/IlaroAdmin/Views/Shared/_Layout.cshtml";
    ViewBag.Title = IlaroAdminResources.Index_Title;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("Breadcrumb", () => {

WriteLiteral("\r\n    <ul");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral(">\r\n        <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">");

            
            #line 11 "..\..\Areas\IlaroAdmin\Views\Group\Index.cshtml"
                      Write(IlaroAdminResources.Index_Title);

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n    </ul>\r\n");

});

WriteLiteral("\r\n<ul");

WriteLiteral(" class=\"list-unstyled\"");

WriteLiteral(">\r\n");

            
            #line 16 "..\..\Areas\IlaroAdmin\Views\Group\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 16 "..\..\Areas\IlaroAdmin\Views\Group\Index.cshtml"
     foreach (var group in Model.Groups)
    {

            
            #line default
            #line hidden
WriteLiteral("        <li");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

            
            #line 19 "..\..\Areas\IlaroAdmin\Views\Group\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 19 "..\..\Areas\IlaroAdmin\Views\Group\Index.cshtml"
              Html.RenderPartial("_GroupPartial", group);
            
            #line default
            #line hidden
WriteLiteral("\r\n        </li>\r\n");

            
            #line 21 "..\..\Areas\IlaroAdmin\Views\Group\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n\r\n");

            
            #line 24 "..\..\Areas\IlaroAdmin\Views\Group\Index.cshtml"
 if (Model.ChangeEnabled)
{
    
            
            #line default
            #line hidden
DefineSection("Sidebar", () => {

WriteLiteral("\r\n");

            
            #line 28 "..\..\Areas\IlaroAdmin\Views\Group\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 28 "..\..\Areas\IlaroAdmin\Views\Group\Index.cshtml"
          Html.RenderPartial("_LastChanges", Model.Changes);
            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

});

            
            #line 29 "..\..\Areas\IlaroAdmin\Views\Group\Index.cshtml"
     
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
